' Half-wave dipole
' CST Studio Suite macro generated by antenlab 0.1.0 from an openEMS project
' model: dipole   created: 2026-09-24T23:18:48+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Checked with CST Studio Suite 2026.2 (history rebuild, solver run); other versions are not tested: please report anything that fails.
'
' Differences to expect vs. openEMS: CST meshes with PBA/TST (conformal) instead of
' staircase cells, and open boundaries add their own space; results agree closely but not
' bit-for-bit.
' Exported openEMS mesh lines: X=57, Y=57, Z=60.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'antenlab-data:' carry the exact openEMS ports, boundaries and mesh
' settings for antenlab's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "antenlab: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""1.5"", ""3.5""" + vbLf
    AddToHistory "antenlab: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "antenlab: background", sCommand

    ' antenlab-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' antenlab-data: {"mesh_lines":{"x":[-84.7,-80.5884,-76.4768,-72.3652,-68.2536,-64.142,-60.0304,-55.9188,-51.8072,-47.6956,-43.584,-39.4724,-35.3608,-31.2492,-27.1376,-23.026,-18.9144,-14.8028,-10.6912,-7.6925,-5.5056,-3.9106,-2.7474,-1.899,-1.2803,-0.8291,-0.5,-0.25,0,0.25,0.5,0.8291,1.2803,1.899,2.7474,3.9106,5.5056,7.6925,10.6912,14.8028]}}
    ' antenlab-data: {"mesh_lines":{"x":[18.9144,23.026,27.1376,31.2492,35.3608,39.4724,43.584,47.6956,51.8072,55.9188,60.0304,64.142,68.2536,72.3652,76.4768,80.5884,84.7]}}
    ' antenlab-data: {"mesh_lines":{"y":[-84.2,-80.1128,-76.0256,-71.9384,-67.8513,-63.7641,-59.6769,-55.5897,-51.5025,-47.4153,-43.3281,-39.2409,-35.1538,-31.0666,-26.9794,-22.8922,-18.805,-14.7178,-10.6306,-7.6498,-5.4759,-3.8904,-2.734,-1.8907,-1.2757,-0.8271,-0.5,-0.25,0,0.25,0.5,0.8271,1.2757,1.8907,2.734,3.8904,5.4759,7.6498,10.6306,14.7178]}}
    ' antenlab-data: {"mesh_lines":{"y":[18.805,22.8922,26.9794,31.0666,35.1538,39.2409,43.3281,47.4153,51.5025,55.5897,59.6769,63.7641,67.8513,71.9384,76.0256,80.1128,84.2]}}
    ' antenlab-data: {"mesh_lines":{"z":[-113.2,-108.9386,-104.6772,-100.4157,-96.1543,-91.8929,-87.6315,-83.37,-79.1086,-74.8472,-70.5858,-66.3244,-62.0629,-57.8015,-53.5401,-49.2787,-45.0172,-40.7558,-36.4944,-33.1121,-30.4276,-28.2862,-25.9283,-22.9576,-19.2146,-15.4717,-11.7288,-7.9859,-4.2429,-0.5,0.5,4.2429,7.9859,11.7288,15.4717,19.2146,22.9576,25.9283,28.2862,30.4276]}}
    ' antenlab-data: {"mesh_lines":{"z":[33.1121,36.4944,40.7558,45.0172,49.2787,53.5401,57.8015,62.0629,66.3244,70.5858,74.8472,79.1086,83.37,87.6315,91.8929,96.1543,100.4157,104.6772,108.9386,113.2]}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "antenlab: boundaries", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""antenlab""" + vbLf
    AddToHistory "new component: antenlab", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""dipole_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""dipole_1""" + vbLf
    sCommand = sCommand + "     .Curve ""dipole_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""0.5"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""29"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""29"", ""0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5"", ""0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""dipole_1""" + vbLf
    sCommand = sCommand + "     .Component ""antenlab""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""dipole_1_curve:dipole_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: antenlab:dipole_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""dipole_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""dipole_2""" + vbLf
    sCommand = sCommand + "     .Curve ""dipole_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-29"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5"", ""0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-29"", ""0.5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-29"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""dipole_2""" + vbLf
    sCommand = sCommand + "     .Component ""antenlab""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""dipole_2_curve:dipole_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: antenlab:dipole_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""antenlab:dipole_1"", ""antenlab:dipole_2""" + vbLf
    AddToHistory "boolean add shapes: antenlab:dipole_1 (+1)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""antenlab:dipole_1"", ""dipole""" + vbLf
    AddToHistory "rename block: antenlab:dipole_1 to: antenlab:dipole", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""73""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""0"", ""0"", ""-0.5""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""0"", ""0"", ""0.5""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' antenlab-data: {"port":1,"type":"lumped","R":73,"start":[-0.5,0,-0.5],"stop":[0.5,0,0.5],"direction":"z"}
    ' far-field monitors at the frequencies analysed in antenlab
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.415)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.415""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.415)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "antenlab: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "antenlab: time domain solver", sCommand

End Sub
