// The running app's version (package.json) and the version that wrote a bundle, for the files an export
// writes now: a drawing, a report, a fab file or a macro is generated by this app, whatever wrote the bundle.
import pkg from "../../package.json" with { type: "json" };

/** The running Fairbeam version (package.json). */
export const APP_VERSION: string = pkg.version;

/** The first Fairbeam release: the bundles shipped as examples were written by earlier, unreleased builds. */
const FIRST_RELEASE = [0, 7, 0];

const parts = (v: string) => v.split(/[.+-]/).slice(0, 3).map((x) => Number.parseInt(x, 10));

/** Whether a version string is at least the first release (0.7.0); false for anything unreadable. */
export function releasedVersion(version: string | null | undefined): boolean {
  if (typeof version !== "string") return false;
  const v = parts(version);
  if (v.length < 3 || v.some((x) => !Number.isFinite(x))) return false;
  for (let i = 0; i < 3; i++) if (v[i] !== FIRST_RELEASE[i]) return v[i] > FIRST_RELEASE[i];
  return true;
}

/** "Fairbeam <version>" of the build that wrote a bundle, or null when that build predates the first
 * release (the bundled examples): its number never named a released version. */
export function bundleWriter(b: { generator?: { version?: string } | null }): string | null {
  const v = b.generator?.version;
  return releasedVersion(v) ? `Fairbeam ${v}` : null;
}
