"""The names Fairbeam still reads from files that antenlab (versions up to 0.6.x) wrote.

Fairbeam is the continuation of antenlab, as a separate program. Its Python package, its
environment variables and everything it writes use the Fairbeam names. What it does not do is
turn away a file the old program made: a design, a project bundle, a study, a CST macro or a
generated Python model that still carries an ``antenlab`` name opens as before. This module is the
one place that knows those names; the readers call it. Nothing here is written to new files.

Not covered, on purpose: ``import antenlab`` in a user's own Python models. The package has no
``antenlab`` alias; the desktop app's import step rewrites such models (the originals are kept).
"""

from __future__ import annotations

# schema id written by antenlab -> the id Fairbeam writes
LEGACY_SCHEMAS = {
    "antenlab.design/1": "fairbeam.design/1",
    "antenlab.project/1": "fairbeam.project/1",
    "antenlab.study/1": "fairbeam.study/1",
    "antenlab.optimization/1": "fairbeam.optimization/1",
    "antenlab.parameter-sweep/1": "fairbeam.parameter-sweep/1",
}

# the metadata comments of an exported CST macro: "' fairbeam-data: {...}" and the
# "' fairbeam-helper: begin|end" markers (antenlab-data / antenlab-helper before 0.7.0)
CST_MARKER_RE = r"(?:fairbeam|antenlab)-data:"
CST_HELPER_RE = r"(?:fairbeam|antenlab)-helper:"
# "CST Studio Suite macro generated by <maker> from ..." in the header of an exported macro
CST_MAKER_RE = r"(?:Fairbeam|antenlab)"

# names that belong to the program itself (dump boxes, helper parts): a user part may not take them
RESERVED_PREFIXES = ("fairbeam_", "antenlab_")

# the module-level attribute of a generated Python model that carries the folder structure
ORGANIZATION_ATTRS = ("FAIRBEAM_ORGANIZATION", "ANTENLAB_ORGANIZATION")


def current_schema(schema):
    """The Fairbeam id for a schema id, whichever program wrote it (other values come back unchanged)."""
    return LEGACY_SCHEMAS.get(schema, schema) if isinstance(schema, str) else schema


def is_legacy_schema(schema) -> bool:
    return isinstance(schema, str) and schema in LEGACY_SCHEMAS


def schema_is(schema, current: str) -> bool:
    """``schema`` is ``current`` or the id antenlab wrote for the same thing."""
    return current_schema(schema) == current


def schema_family(schema, family: str) -> bool:
    """``schema`` is any version of a family such as ``"fairbeam.project/"`` (or its antenlab spelling)."""
    if not isinstance(schema, str):
        return False
    legacy = "antenlab." + family[len("fairbeam."):] if family.startswith("fairbeam.") else family
    return schema.startswith(family) or schema.startswith(legacy)


def is_reserved_name(name) -> bool:
    return isinstance(name, str) and name.startswith(RESERVED_PREFIXES)


def organization_of(module):
    """The organization metadata of a generated model (``FAIRBEAM_ORGANIZATION``, or the
    ``ANTENLAB_ORGANIZATION`` of a file exported by antenlab); ``(name, value)`` or ``(None, None)``."""
    for attr in ORGANIZATION_ATTRS:
        if hasattr(module, attr):
            return attr, getattr(module, attr)
    return None, None

