// README.md report for the export package: a readable summary of model, setup, run and results.

import { withoutVoids } from "../lib/voidParts.ts";
import type { Bundle } from "../types";
import { efficiencyWarning, energyText, finalEnergy } from "../lib/run.ts";

const f3 = (hz: number) => (hz / 1e9).toFixed(3);
const fx = (v: number | null | undefined, d = 2) => (v === null || v === undefined || !Number.isFinite(v) ? "—" : v.toFixed(d));
const esc = (s: string) => s.replace(/\|/g, "\\|");
const table = (head: string[], rows: (string | number)[][], align?: ("l" | "r")[]) =>
  [
    `| ${head.map(esc).join(" | ")} |`,
    `| ${head.map((_, i) => (align?.[i] === "r" ? "---:" : "---")).join(" | ")} |`,
    ...rows.map((r) => `| ${r.map((c) => esc(String(c))).join(" | ")} |`),
  ].join("\n");

const shellArg = (s: string) => (/^[A-Za-z0-9._,+\-=/]+$/.test(s) ? s : `'${s.replace(/'/g, "'\\''")}'`);

/** Model file of the built-in models: python/models/<id with "-" replaced by "_">.py (an assumption for custom models). */
export const modelPath = (b: Bundle) => `python/models/${b.model.id.replace(/-/g, "_")}.py`;

/** Reconstruct the `fairbeam run` command: non-default parameters, plus --points/--pattern when not default. */
export function reproduceCommand(b: Bundle): string {
  const args = ["fairbeam", "run", modelPath(b)];
  for (const p of b.model.params) if (p.value !== p.default) args.push("--set", shellArg(`${p.key}=${p.value}`));
  const r = b.results;
  if (r) {
    if (r.frequency.length !== 801) args.push("--points", String(r.frequency.length));
    const centres = r.bands.slice(0, 4).map((x) => Math.round(x.f_center / 1e6));
    // one pattern per driven port shares a frequency: name each frequency once
    const ff = [...new Set(r.farfield.map((x) => Math.round(x.f / 1e6)))];
    const sameAsBands = centres.length > 0 && centres.length === ff.length && centres.every((c, i) => c === ff[i]);
    if (!sameAsBands && ff.length && r.bands.length) args.push("--pattern", `"${ff.map((m) => m / 1000).join(",")}"`);
  }
  // surface-current maps are only written on request
  if (b.fields?.planes?.length) args.push("--fields");
  if (b.run?.threads) args.push("--threads", String(b.run.threads));
  return args.join(" ");
}

export interface ReportOptions {
  exported: string;
  files: { path: string; description: string }[];
}

export function readmeReport(bundle: Bundle, opt: ReportOptions): string {
  const b = withoutVoids(bundle);
  const out: string[] = [];
  const push = (...l: string[]) => out.push(...l);
  push(`# ${b.name}`, "");
  push(`Export package generated by **Fairbeam ${b.generator.version}** on ${opt.exported}. The simulation ran on ${b.created}.`, "");
  push(`- **Model:** \`${b.model.id}\` — ${b.model.name}`);
  push(`- **Description:** ${b.model.description}`);
  if (b.model.reference) push(`- **Reference:** ${b.model.reference}`);
  push(`- **Schema:** \`${b.schema}\` (field reference: docs/BUNDLE.md in the Fairbeam source repository)`, "");

  push("## Parameters", "");
  push(
    table(
      ["Key", "Label", "Value", "Default", "Unit", "Range"],
      b.model.params.map((p) => [
        `\`${p.key}\``, p.label, `${p.value}${p.value !== p.default ? " *" : ""}`, String(p.default), p.unit || "—",
        p.minimum === null && p.maximum === null ? "—" : `${p.minimum ?? "−∞"} … ${p.maximum ?? "∞"}`,
      ]),
      ["l", "l", "r", "r", "l", "l"],
    ),
  );
  if (b.model.params.some((p) => p.value !== p.default)) push("", "\\* differs from the model default.");
  push("");

  push("## Geometry and materials", "");
  push(
    table(
      ["Part", "Type", "Primitives", "εr", "tan δ", "Size (mm)"],
      b.parts.map((p) => [
        p.label ?? p.name,
        p.type === "Material" ? "Dielectric" : p.type === "Metal" ? "PEC" : p.type,
        p.primitives.length + (p.primitives.some((q) => !q.exact) ? " (approx.)" : ""),
        p.material ? String(p.material.eps_r) : "—",
        p.material?.tan_d != null ? `${p.material.tan_d}${p.material.tan_d_freq ? ` @ ${f3(p.material.tan_d_freq)} GHz` : ""}` : "—",
        p.bbox[1].map((v, i) => Number((v - p.bbox[0][i]).toFixed(3))).join(" × "),
      ]),
    ),
  );
  if (b.half_space) push("", `Infinite **${b.half_space.kind} ground plane** at z = ${b.half_space.position} mm (the ${b.half_space.axis}${b.half_space.side === "min" ? "−" : "+"} boundary; image theory). It is a boundary condition, not a part.`);
  push("", table(["Port", "Type", "R (Ω)", "Direction", "Start (mm)", "Stop (mm)", "Excited"], b.ports.map((p) => [p.number, p.type, p.R, p.direction, p.start.join(", "), p.stop.join(", "), p.excite ? "yes" : "no"])), "");

  push("## Solver settings", "");
  const ex = b.solver.excitation;
  push(`- **Engine:** ${b.solver.engine}${b.generator.openems ? ` ${b.generator.openems}` : ""}${b.generator.csxcad ? ` (CSXCAD ${b.generator.csxcad})` : ""}, Python ${b.generator.python}`);
  push(`- **Method:** ${b.solver.method}`);
  push(`- **Excitation:** ${ex.type}${ex.dc_free ? " (DC-free)" : ""}, band ${f3(ex.f_min)} – ${f3(ex.f_max)} GHz${ex.f0 ? `, f0 = ${f3(ex.f0)} GHz, fc = ${f3(ex.fc ?? 0)} GHz` : ""}`);
  push(`- **Boundaries:** ${Object.entries(b.solver.boundaries).map(([k, v]) => `${k} ${v}`).join(", ")}`);
  push(`- **End criterion:** ${b.solver.end_criteria_db} dB field energy, at most ${b.solver.max_timesteps} timesteps`, "");

  push("## Mesh", "");
  push(`- **Cells:** ${b.mesh.cells.join(" × ")} = ${b.mesh.total_cells.toLocaleString("en-US")}`);
  push(`- **Cell size:** ${fx(b.mesh.min_cell, 4)} – ${fx(b.mesh.max_cell, 3)} mm`);
  push(`- **Domain:** (${b.domain.min.join(", ")}) to (${b.domain.max.join(", ")}) mm`, "");

  push("## Run", "");
  if (b.run) {
    const r = b.run;
    const e = finalEnergy(r, b.solver.end_criteria_db);
    push(`- **Converged:** ${r.converged ? "yes" : "no"}${r.hit_timestep_limit ? " (stopped at the timestep limit)" : ""}${e.db !== null ? `, ${r.converged ? "final" : "last logged"} energy ${energyText(e)}` : ""}`);
    push(`- **Timesteps:** ${r.timesteps ?? "—"}`);
    push(`- **Solver time:** ${fx(r.solver_time_s, 2)} s (wall ${fx(r.wall_time_s, 2)} s)`);
    push(`- **Throughput:** ${fx(r.speed_mcells_s, 1)} MCells/s, threads ${r.threads || "all"}`);
    push(`- **Host:** ${r.host.os} ${r.host.machine}${r.host.cpu ? `, ${r.host.cpu}` : ""}`, "");
  } else push("Geometry only: this bundle was not simulated.", "");

  push("## Results", "");
  const res = b.results;
  if (res) {
    push(`${res.frequency.length} frequency points, ${f3(res.frequency[0])} – ${f3(res.frequency[res.frequency.length - 1])} GHz.`, "");
    push("### Matched bands (|S11| < −10 dB)", "");
    push(
      res.bands.length
        ? table(
            ["f_lo (GHz)", "f_hi (GHz)", "Centre (GHz)", "S11 min (dB)", "Bandwidth (MHz)", "Fractional BW (%)", "Note"],
            res.bands.map((x) => [f3(x.f_lo), f3(x.f_hi), f3(x.f_center), fx(x.s11_min_db, 2), fx((x.f_hi - x.f_lo) / 1e6, 1), fx(x.fractional_bw * 100, 2), x.edge_lo || x.edge_hi ? "touches the simulated range" : ""]),
            ["r", "r", "r", "r", "r", "r", "l"],
          )
        : "No band reaches −10 dB.",
      "",
    );
    push("### Far field", "");
    push(
      res.farfield.length
        ? table(
            [...(res.farfield.some((x) => x.port != null) ? ["Port"] : []), "f (GHz)", "Dmax (dBi)", "Gain (dBi)", "Realized gain (dBi)", "Rad. efficiency (%)", "Mirror planes"],
            res.farfield.map((x) => [...(res.farfield.some((y) => y.port != null) ? [x.port != null ? `P${x.port}` : "—"] : []), f3(x.f), fx(x.dmax_dbi), fx(x.gain_dbi), fx(x.realized_gain_dbi), x.rad_efficiency === null ? "—" : fx(x.rad_efficiency * 100, 1), x.mirror_planes ?? 0]),
            [...(res.farfield.some((x) => x.port != null) ? ["l"] : []), "r", "r", "r", "r", "r", "r"] as ("l" | "r")[],
          )
        : "No far-field data.",
      "",
    );
    const effWarn = res.farfield.map((ff) => efficiencyWarning(ff)).filter((w): w is string => w !== null);
    if (effWarn.length) push(...effWarn.map((w) => `> **QA warning:** ${w}`), "");
    if (res.farfield.some((x) => (x.mirror_planes ?? 0) > 0)) {
      push(
        "**Half-space / mirror correction.** With PEC or PMC boundaries openEMS mirrors the NF2FF recording surface and integrates the image too. Fairbeam divides the radiated power by 2^m and multiplies Dmax by 2^m (m = number of mirror planes), so directivity, efficiency and gain refer to the physical half space (for example a monopole over an infinite ground). Patterns are defined for θ ≤ 90° only.",
        "",
      );
    }
    push("Gain = efficiency · Dmax; realized gain = gain · (1 − |S11|²); radiation efficiency = P_rad / P_acc.", "");
  } else push("No results (geometry only).", "");

  push("## Files", "");
  push(table(["File", "Contents"], opt.files.map((f) => [`\`${f.path}\``, f.description])), "");
  push("Touchstone: `data/s11.s1p` is Touchstone v1 (`# GHz S RI R 50`): frequency in GHz, then Re and Im of S11. Most RF tools read it directly, so it can be overlaid on other S11 results.", "");
  push("## Reproduce", "");
  push("```bash", reproduceCommand(b), "```", "");
  push(
    `Assumes the built-in model layout: the model file is \`${modelPath(b)}\` (model id with "-" replaced by "_"). For a custom model, pass its path instead. Only parameters that differ from the defaults are listed; \`project.json\` holds the full setup.`,
    "",
  );
  return out.join("\n");
}
