' Blade antenna (867 MHz, mesh-sensitive)
' CST-compatible VBA macro generated by Fairbeam 0.7.2 from an openEMS project
' model: blade-867   created: 2026-10-09T00:28:58+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=77, Y=61, Z=60.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.7"", ""1.05""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"MUR","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-257.0687,-243.2662,-229.4636,-215.6611,-201.8585,-188.056,-174.2801,-162.9294,-154.7586,-147.6207,-139.853,-129.2117,-116.0772,-102.8591,-89.6411,-76.4231,-63.2051,-50.8372,-41.6285,-34.9069,-30,-25.9924,-22.8621,-19.7023,-16.0413,-12.2665,-9.1466,-6.7815,-5.0194,-3.7067,-2.7287,-2,-1.4056,-0.9172,-0.4377,0,0.4388,0.9204,1.4115,2]}}
    ' fairbeam-data: {"mesh_lines":{"x":[2.6709,3.5531,4.7134,6.2382,8.0582,10,11.7198,13.8571,16.3996,19.9654,24.0128,27.1033,28.5082,30,32.1692,34.2412,36.7351,40,44.3803,50.5089,59.0856,71.0867,85.1941,99.3015,113.4089,127.5066,139.2375,147.6207,154.7586,162.9294,174.2801,188.056,201.8585,215.6611,229.4636,243.2662,257.0687]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-257.0687,-243.2662,-229.4636,-215.6611,-201.8585,-188.056,-174.2801,-162.9294,-154.7586,-147.6207,-139.1405,-127.2349,-112.994,-98.7481,-85.3099,-71.8717,-58.4335,-45.0027,-33.5266,-24.9285,-18.486,-13.6586,-10.0419,-7.3314,-5.3012,-3.7792,-2.6396,-1.7853,-1.1434,-0.5717,0,0.5717,1.1434,1.7853,2.6396,3.7792,5.3012,7.3314,10.0419,13.6586]}}
    ' fairbeam-data: {"mesh_lines":{"y":[18.486,24.9285,33.5266,45.0027,58.4335,71.8717,85.3099,98.7481,112.994,127.2349,139.1405,147.6207,154.7586,162.9294,174.2801,188.056,201.8585,215.6611,229.4636,243.2662,257.0687]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-107.0687,-92.8625,-78.6562,-64.4499,-50.2582,-36.8359,-26.6622,-19.1655,-13.6423,-9.5722,-6.5736,-4.3639,-2.7356,-1.5359,-0.6516,0,0.5,1,1.5,2,2.5776,3.3381,4.3393,5.6576,7.3932,9.6303,11.8836,14,16.502,19.6572,23.4137,27.1065,30.5517,34.033,37.6896,41.3164,44.8275,48.358,51.9654,55.5515]}}
    ' fairbeam-data: {"mesh_lines":{"z":[59.1033,62.67,66.2412,69.7949,73.3792,76.9786,79.6207,82,84.0764,86.7586,90.1083,94.7221,101.0776,109.8315,121.8426,135.2878,148.7331,162.1783,175.6235,189.0687]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":20,"pad":107.06873499999999,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""ground_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""ground""" + vbLf
    sCommand = sCommand + "     .Curve ""ground_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-150"", ""-150""" + vbLf
    sCommand = sCommand + "     .LineTo ""150"", ""-150""" + vbLf
    sCommand = sCommand + "     .LineTo ""150"", ""150""" + vbLf
    sCommand = sCommand + "     .LineTo ""-150"", ""150""" + vbLf
    sCommand = sCommand + "     .LineTo ""-150"", ""-150""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""ground""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""ground_curve:ground""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:ground", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""blade_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""blade""" + vbLf
    sCommand = sCommand + "     .Curve ""blade_curve""" + vbLf
    sCommand = sCommand + "     .Point ""2"", ""-2""" + vbLf
    sCommand = sCommand + "     .LineTo ""2"", ""2""" + vbLf
    sCommand = sCommand + "     .LineTo ""14"", ""30""" + vbLf
    sCommand = sCommand + "     .LineTo ""82"", ""40""" + vbLf
    sCommand = sCommand + "     .LineTo ""82"", ""10""" + vbLf
    sCommand = sCommand + "     .LineTo ""14"", ""-30""" + vbLf
    sCommand = sCommand + "     .LineTo ""2"", ""-2""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""blade""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""blade_curve:blade""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:blade", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port; P1/P2 lie on the port axis)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""0"", ""0"", ""2""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[0,0,0],"stop":[0,0,2],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=0.867)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""0.867""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=0.867)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-50""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
