' Branch-line coupler (2.4 GHz)
' CST-compatible VBA macro generated by Fairbeam 0.2.0 from an openEMS project
' model: branchline-coupler   created: 2026-09-25T21:20:31+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=52, Y=54, Z=29.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""1"", ""4""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"MUR","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-32.6439,-29.2226,-25.8014,-22.8259,-20.6439,-18.6307,-16.6175,-14.7001,-13.2778,-12.2612,-11.5345,-11.0151,-10.6439,-10.3275,-10.0112,-9.6949,-9.3786,-9.0623,-8.7459,-8.3818,-7.8753,-7.1705,-6.1898,-4.8252,-2.9704,-0.9901,0.9901,2.9704,4.8252,6.1898,7.1705,7.8753,8.3818,8.7459,9.0623,9.3786,9.6949,10.0112,10.3275,10.6439]}}
    ' fairbeam-data: {"mesh_lines":{"x":[11.0151,11.5345,12.2612,13.2778,14.7001,16.6175,18.6307,20.6439,22.8259,25.8014,29.2226,32.6439]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-29.47,-26.0359,-22.6017,-19.6394,-17.47,-15.6767,-14.2636,-13.2218,-12.4538,-11.8875,-11.47,-11.116,-10.8387,-10.5224,-10.2061,-9.8898,-9.5734,-9.2571,-8.9408,-8.6658,-8.3095,-7.8323,-7.162,-6.2205,-4.8979,-3.0562,-1.0187,1.0187,3.0562,4.8979,6.2205,7.162,7.8323,8.3095,8.6658,8.9408,9.2571,9.5734,9.8898,10.2061]}}
    ' fairbeam-data: {"mesh_lines":{"y":[10.5224,10.8387,11.116,11.47,11.8875,12.4538,13.2218,14.2636,15.6767,17.47,19.6394,22.6017,26.0359,29.47]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-12,-8.6605,-6.1629,-4.3488,-3.0311,-2.0739,-1.3787,-0.8738,-0.5069,-0.2405,0,0.2032,0.4065,0.6098,0.813,0.985,1.1293,1.2735,1.4456,1.6271,1.8665,2.1842,2.6292,3.2529,4.1266,5.3508,7.0661,9.4695,12.813]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":20,"pad":12,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.0027 at 2.4 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""3.38""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.001218485329""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-20.643855"", ""20.643855""" + vbLf
    sCommand = sCommand + "     .Yrange ""-17.470003"", ""17.470003""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-20.643855"", ""-17.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.643855"", ""-17.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.643855"", ""17.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.643855"", ""17.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.643855"", ""-17.470003""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_1""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-10.643855"", ""8.309508""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""8.309508""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""8.309508""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_1_curve:coupler_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_2""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""8.745949"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""8.745949"", ""11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""8.745949"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_2_curve:coupler_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_3""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-10.643855"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""-8.309508""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""-8.309508""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_3_curve:coupler_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_4""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-10.643855"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-8.745949"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-8.745949"", ""11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""11.470003""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""-11.470003""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_4_curve:coupler_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_5_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_5""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_5_curve""" + vbLf
    sCommand = sCommand + "     .Point ""10.643855"", ""8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.643855"", ""8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.643855"", ""10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""8.940803""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_5_curve:coupler_5""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_6_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_6""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_6_curve""" + vbLf
    sCommand = sCommand + "     .Point ""10.643855"", ""-10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.643855"", ""-10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.643855"", ""-8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""-8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""10.643855"", ""-10.838708""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_6_curve:coupler_6""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_7_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_7""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_7_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-20.643855"", ""8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.643855"", ""10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.643855"", ""8.940803""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_7""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_7_curve:coupler_7""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_7", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coupler_8_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_8""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_8_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-20.643855"", ""-10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""-10.838708""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10.643855"", ""-8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.643855"", ""-8.940803""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.643855"", ""-10.838708""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coupler_8""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coupler_8_curve:coupler_8""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coupler_8", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_6""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_7""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:coupler_1"", ""fairbeam:coupler_8""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:coupler_1 (+7)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:coupler_1"", ""coupler""" + vbLf
    AddToHistory "rename block: fairbeam:coupler_1 to: fairbeam:coupler", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-20.64385459"", ""9.889755661"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-20.64385459"", ""9.889755661"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-20.64385458504718,8.94080310074361,0],"stop":[-20.64385458504718,10.838708221316198,0.813],"direction":"z"}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""2""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""20.64385459"", ""9.889755661"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""20.64385459"", ""9.889755661"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 2", sCommand

    ' fairbeam-data: {"port":2,"type":"lumped","R":50,"start":[20.64385458504718,8.94080310074361,0],"stop":[20.64385458504718,10.838708221316198,0.813],"direction":"z","excite":false}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""3""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""20.64385459"", ""-9.889755661"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""20.64385459"", ""-9.889755661"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 3", sCommand

    ' fairbeam-data: {"port":3,"type":"lumped","R":50,"start":[20.64385458504718,-10.838708221316198,0],"stop":[20.64385458504718,-8.94080310074361,0.813],"direction":"z","excite":false}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""4""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-20.64385459"", ""-9.889755661"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-20.64385459"", ""-9.889755661"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 4", sCommand

    ' fairbeam-data: {"port":4,"type":"lumped","R":50,"start":[-20.64385458504718,-10.838708221316198,0],"stop":[-20.64385458504718,-8.94080310074361,0.813],"direction":"z","excite":false}
    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
