' UAV printed 2-element collinear (867 MHz)
' CST-compatible VBA macro generated by Fairbeam 0.5.6 from an openEMS project
' model: collinear-867   created: 2026-10-03T18:05:48+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=127, Y=84, Z=332.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.75"", ""1""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-194.8755,-185.0199,-175.1644,-165.3088,-155.4533,-145.5977,-135.7422,-125.8866,-116.0311,-106.1755,-96.32,-86.4644,-76.6088,-66.7533,-56.8977,-47.0422,-37.5605,-30.4528,-25.3684,-21.7343,-19.1369,-17.2777,-15.9515,-15,-14.2767,-13.729,-13.3142,-13,-12.6667,-12.3333,-12,-11.6667,-11.3333,-11,-10.6591,-10.1998,-9.6064,-9.0235,-8.4456,-8]}}
    ' fairbeam-data: {"mesh_lines":{"x":[-7.5464,-7.1968,-6.8947,-6.6064,-6.2737,-5.8667,-5.492,-5.104,-4.8,-4.4697,-4.1968,-3.9586,-3.7333,-3.4765,-3.1311,-2.6667,-2.1239,-1.6,-1.1523,-0.8309,-0.6,-0.4,-0.2,0,0.2,0.4,0.6,0.8309,1.1523,1.6,2.1239,2.6667,3.1311,3.4765,3.7333,3.9586,4.1968,4.4697,4.8,5.104]}}
    ' fairbeam-data: {"mesh_lines":{"x":[5.492,5.8667,6.2737,6.6064,6.8947,7.1968,7.5464,8,8.4456,9.0235,9.6064,10.1998,10.6591,11,11.3333,11.6667,12,12.3333,12.6667,13,13.3142,13.729,14.2767,15,15.9515,17.2777,19.1369,21.7343,25.3684,30.4528,37.5605,47.0422,56.8977,66.7533,76.6088,86.4644,96.32,106.1755,116.0311,125.8866]}}
    ' fairbeam-data: {"mesh_lines":{"x":[135.7422,145.5977,155.4533,165.3088,175.1644,185.0199,194.8755]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-181.4755,-171.8152,-162.155,-152.4947,-142.8345,-133.1743,-123.514,-113.8538,-104.1935,-94.5333,-84.8731,-75.2128,-65.5526,-55.8923,-46.2321,-36.5718,-27.2023,-20.0705,-14.9382,-11.2429,-8.5843,-6.6682,-5.2897,-4.3045,-3.5962,-3.082,-2.7315,-2.485,-2.3092,-2.1333,-2,-1.8898,-1.8,-1.7105,-1.6,-1.4793,-1.3333,-1.192,-1.0667,-0.9398]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-0.8,-0.6602,-0.5333,-0.408,-0.2667,-0.1206,0,0.1104,0.2,0.2899,0.4,0.518,0.6667,0.8198,1,1.1819,1.4193,1.7291,2.1333,2.6507,3.3624,4.344,5.7159,7.6236,10.267,13.9373,19.0297,26.0992,35.4151,45.0458,54.6765,64.3072,73.9379,83.5686,93.1993,102.83,112.4606,122.0913,131.722,141.3527]}}
    ' fairbeam-data: {"mesh_lines":{"y":[150.9834,160.6141,170.2448,179.8755]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-253.6755,-243.6986,-233.7218,-223.7449,-213.768,-203.7912,-193.8143,-183.8375,-173.8606,-163.8838,-153.9069,-143.93,-133.9532,-123.9763,-113.9995,-104.0226,-94.1205,-86.2466,-80.6384,-76.6459,-73.8,-71.4064,-68.9968,-66.2948,-62.5626,-58,-53.4112,-48.8224,-44.2336,-39.6448,-35.056,-30.4672,-25.8784,-21.2896,-16.7009,-12.7816,-9.9463,-7.8954,-6.4116,-5.3383]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-4.5621,-4,-3.5,-3,-2.5,-2,-1.5,-1,-0.5645,0,0.5645,1,1.5,2,2.5903,3.4149,4.5707,6.1903,8.4596,11.6396,16.0303,20.8097,25.5891,30.3685,35.1479,39.9273,44.7067,49.4861,54.2655,58.417,61.3831,63.5002,65.0111,66.0886,66.8579,67.4061,67.8,68.1333,68.4667,68.8]}}
    ' fairbeam-data: {"mesh_lines":{"z":[69.1333,69.4667,69.8,70.1066,70.4667,70.8283,71.2996,71.8,72.3004,72.7717,73.1333,73.4934,73.8,74.1333,74.4667,74.8,75.1333,75.4667,75.8,76.1066,76.4667,76.8283,77.2996,77.8,78.3004,78.7717,79.1333,79.4934,79.8,80.1333,80.4667,80.8,81.1333,81.4667,81.8,82.1066,82.4667,82.8283,83.2996,83.8]}}
    ' fairbeam-data: {"mesh_lines":{"z":[84.3004,84.7717,85.1333,85.4934,85.8,86.1333,86.4667,86.8,87.1333,87.4667,87.8,88.1066,88.4667,88.8283,89.2996,89.8,90.3004,90.7717,91.1333,91.4934,91.8,92.1333,92.4667,92.8,93.1333,93.4667,93.8,94.1066,94.4667,94.8283,95.2996,95.8,96.3004,96.7717,97.1333,97.4934,97.8,98.1333,98.4667,98.8]}}
    ' fairbeam-data: {"mesh_lines":{"z":[99.1333,99.4667,99.8,100.1066,100.4667,100.8283,101.2996,101.8,102.3004,102.7717,103.1333,103.4934,103.8,104.1333,104.4667,104.8,105.1333,105.4667,105.8,106.1066,106.4667,106.8283,107.2996,107.8,108.3004,108.7717,109.1333,109.4934,109.8,110.1333,110.4667,110.8,111.1333,111.4667,111.8,112.1066,112.4667,112.8283,113.2996,113.8]}}
    ' fairbeam-data: {"mesh_lines":{"z":[114.3004,114.7717,115.1333,115.4934,115.8,116.1333,116.4667,116.8,117.1333,117.4667,117.8,118.1066,118.4667,118.8283,119.2996,119.8,120.3004,120.7717,121.1333,121.4934,121.8,122.1333,122.4667,122.8,123.1333,123.4667,123.8,124.1066,124.4667,124.8283,125.2996,125.8,126.3004,126.7717,127.1333,127.4934,127.8,128.1333,128.4667,128.8]}}
    ' fairbeam-data: {"mesh_lines":{"z":[129.1333,129.4667,129.8,130.1066,130.4667,130.8283,131.2996,131.8,132.3004,132.7717,133.1333,133.4934,133.8,134.1333,134.4667,134.8,135.1333,135.4667,135.8,136.1066,136.4667,136.8283,137.2996,137.8,138.3004,138.7717,139.1333,139.4934,139.8,140.1333,140.4667,140.8,141.1333,141.4667,141.8,142.1889,142.7327,143.4864,144.5465,146.0323]}}
    ' fairbeam-data: {"mesh_lines":{"z":[148.1124,151.0257,155.0996,159.864,164.6284,169.3927,174.1571,178.9215,183.6858,188.4502,193.2146,197.9789,202.7433,207.5077,212.272,217.0364,221.8008,226.5651,231.3295,236.0939,240.8582,245.6226,250.387,255.1513,259.9157,264.68,269.4444,274.2036,278.1657,280.9968,283.4064,285.8,288.6459,292.6384,298.2466,306.1205,316.0226,325.9995,335.9763,345.9532]}}
    ' fairbeam-data: {"mesh_lines":{"z":[355.93,365.9069,375.8838,385.8606,395.8375,405.8143,415.7912,425.768,435.7449,445.7218,455.6986,465.6755]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":30,"pad":99.93081933333333,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' board: equivalent tan d = 0.02 at 0.867 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""4.3""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.004148070674""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: board", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""board""" + vbLf
    sCommand = sCommand + "     .Xrange ""-15"", ""15""" + vbLf
    sCommand = sCommand + "     .Yrange ""-1.6"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-73.8"", ""285.8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:board", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""dipole_arm_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""dipole_arm""" + vbLf
    sCommand = sCommand + "     .Curve ""dipole_arm_curve""" + vbLf
    sCommand = sCommand + "     .Point ""1"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""69.8"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""69.8"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""-5""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""dipole_arm""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""dipole_arm_curve:dipole_arm""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:dipole_arm", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""sleeve_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_1""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-4"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-1"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-1"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_1_curve:sleeve_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:sleeve_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""sleeve_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_2""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-69.8"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-1.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""-1.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""-8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_2_curve:sleeve_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:sleeve_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""sleeve_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_3""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-69.8"", ""1.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""1.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""1.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_3_curve:sleeve_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:sleeve_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:sleeve_1"", ""fairbeam:sleeve_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:sleeve_1"", ""fairbeam:sleeve_3""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:sleeve_1 (+2)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:sleeve_1"", ""sleeve""" + vbLf
    AddToHistory "rename block: fairbeam:sleeve_1 to: fairbeam:sleeve", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_ends_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_ends_1""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_ends_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""67.8"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""69.8"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""69.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""67.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""67.8"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_ends_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_ends_1_curve:meander_ends_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_ends_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_ends_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_ends_2""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_ends_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""139.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""141.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""141.8"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""139.8"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""139.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_ends_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_ends_2_curve:meander_ends_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_ends_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_ends_1"", ""fairbeam:meander_ends_2""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:meander_ends_1 (+1)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:meander_ends_1"", ""meander_ends""" + vbLf
    AddToHistory "rename block: fairbeam:meander_ends_1 to: fairbeam:meander_ends", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_1""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""73.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""75.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""75.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""73.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""73.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_1_curve:meander_rungs_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_2""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""79.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""81.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""81.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""79.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""79.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_2_curve:meander_rungs_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_3""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""85.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""87.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""87.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""85.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""85.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_3_curve:meander_rungs_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_4""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""91.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""93.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""93.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""91.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""91.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_4_curve:meander_rungs_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_5_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_5""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_5_curve""" + vbLf
    sCommand = sCommand + "     .Point ""97.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""99.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""99.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""97.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""97.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_5_curve:meander_rungs_5""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_6_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_6""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_6_curve""" + vbLf
    sCommand = sCommand + "     .Point ""103.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""105.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""105.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""103.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""103.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_6_curve:meander_rungs_6""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_7_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_7""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_7_curve""" + vbLf
    sCommand = sCommand + "     .Point ""109.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""111.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""111.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""109.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""109.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_7""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_7_curve:meander_rungs_7""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_7", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_8_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_8""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_8_curve""" + vbLf
    sCommand = sCommand + "     .Point ""115.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""117.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""117.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""115.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""115.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_8""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_8_curve:meander_rungs_8""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_8", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_9_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_9""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_9_curve""" + vbLf
    sCommand = sCommand + "     .Point ""121.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""123.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""123.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""121.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""121.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_9""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_9_curve:meander_rungs_9""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_9", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_10_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_10""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_10_curve""" + vbLf
    sCommand = sCommand + "     .Point ""127.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""129.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""129.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""127.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""127.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_10""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_10_curve:meander_rungs_10""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_10", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_rungs_11_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_11""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_11_curve""" + vbLf
    sCommand = sCommand + "     .Point ""133.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""135.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""135.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""133.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""133.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_rungs_11""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_rungs_11_curve:meander_rungs_11""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_rungs_11", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_6""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_7""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_8""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_9""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_10""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_rungs_1"", ""fairbeam:meander_rungs_11""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:meander_rungs_1 (+10)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:meander_rungs_1"", ""meander_rungs""" + vbLf
    AddToHistory "rename block: fairbeam:meander_rungs_1 to: fairbeam:meander_rungs", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_right_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_1""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""67.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""75.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""75.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""67.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""67.8"", ""11""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_1_curve:meander_links_right_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_right_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_right_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_2""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""79.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""87.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""87.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""79.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""79.8"", ""11""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_2_curve:meander_links_right_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_right_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_right_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_3""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""91.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""99.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""99.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""91.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""91.8"", ""11""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_3_curve:meander_links_right_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_right_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_right_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_4""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""103.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""111.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""111.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""103.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""103.8"", ""11""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_4_curve:meander_links_right_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_right_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_right_5_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_5""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_5_curve""" + vbLf
    sCommand = sCommand + "     .Point ""115.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""123.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""123.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""115.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""115.8"", ""11""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_5_curve:meander_links_right_5""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_right_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_right_6_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_6""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_6_curve""" + vbLf
    sCommand = sCommand + "     .Point ""127.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""135.8"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""135.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""127.8"", ""13""" + vbLf
    sCommand = sCommand + "     .LineTo ""127.8"", ""11""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_right_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_right_6_curve:meander_links_right_6""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_right_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_right_1"", ""fairbeam:meander_links_right_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_right_1"", ""fairbeam:meander_links_right_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_right_1"", ""fairbeam:meander_links_right_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_right_1"", ""fairbeam:meander_links_right_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_right_1"", ""fairbeam:meander_links_right_6""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:meander_links_right_1 (+5)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:meander_links_right_1"", ""meander_links_right""" + vbLf
    AddToHistory "rename block: fairbeam:meander_links_right_1 to: fairbeam:meander_links_right", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_left_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_1""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""73.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""81.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""81.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""73.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""73.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_1_curve:meander_links_left_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_left_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_left_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_2""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""85.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""93.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""93.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""85.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""85.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_2_curve:meander_links_left_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_left_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_left_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_3""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""97.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""105.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""105.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""97.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""97.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_3_curve:meander_links_left_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_left_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_left_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_4""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""109.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""117.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""117.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""109.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""109.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_4_curve:meander_links_left_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_left_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_left_5_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_5""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_5_curve""" + vbLf
    sCommand = sCommand + "     .Point ""121.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""129.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""129.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""121.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""121.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_5_curve:meander_links_left_5""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_left_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""meander_links_left_6_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_6""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_6_curve""" + vbLf
    sCommand = sCommand + "     .Point ""133.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""141.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .LineTo ""141.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""133.8"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""133.8"", ""-13""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""meander_links_left_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""meander_links_left_6_curve:meander_links_left_6""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:meander_links_left_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_left_1"", ""fairbeam:meander_links_left_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_left_1"", ""fairbeam:meander_links_left_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_left_1"", ""fairbeam:meander_links_left_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_left_1"", ""fairbeam:meander_links_left_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:meander_links_left_1"", ""fairbeam:meander_links_left_6""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:meander_links_left_1 (+5)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:meander_links_left_1"", ""meander_links_left""" + vbLf
    AddToHistory "rename block: fairbeam:meander_links_left_1 to: fairbeam:meander_links_left", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""top_element_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""top_element""" + vbLf
    sCommand = sCommand + "     .Curve ""top_element_curve""" + vbLf
    sCommand = sCommand + "     .Point ""139.8"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""281.8"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""281.8"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""139.8"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""139.8"", ""-5""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""top_element""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""top_element_curve:top_element""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:top_element", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coax_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coax""" + vbLf
    sCommand = sCommand + "     .Curve ""coax_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-73.8"", ""-0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-73.8"", ""0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-73.8"", ""-0.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coax""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coax_curve:coax""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coax", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""feed_trace_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""-1.6"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""feed_trace""" + vbLf
    sCommand = sCommand + "     .Curve ""feed_trace_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-58"", ""-0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""2"", ""-0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""2"", ""0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-58"", ""0.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-58"", ""-0.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""feed_trace""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""feed_trace_curve:feed_trace""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:feed_trace", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""feed_via_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.5""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""feed_via""" + vbLf
    sCommand = sCommand + "     .Curve ""feed_via_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-0.6"", ""-1.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.6"", ""-1.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.6"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.6"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.6"", ""-1.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""feed_via""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""feed_via_curve:feed_via""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:feed_via", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""0"", ""-1.6"", ""-58""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""0"", ""0"", ""-58""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-0.6,-1.6,-58],"stop":[0.6,0,-58],"direction":"y"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=0.867)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""0.867""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=0.867)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
