' Axial-mode helix (2.4 GHz, RHCP)
' CST-compatible VBA macro generated by Fairbeam 0.1.0 from an openEMS project
' model: helix-axial   created: 2026-09-25T03:08:51+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=91, Y=91, Z=168.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""1.8"", ""3""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-118.2861,-114.9971,-111.7081,-108.4191,-105.1301,-101.8411,-98.5521,-95.2631,-91.9741,-88.6851,-85.3961,-82.1071,-78.8181,-75.5291,-72.2402,-68.9512,-65.6622,-62.3732,-59.0842,-55.7978,-53.0647,-51.1103,-49.4448,-47.6667,-45.243,-42.235,-39.2009,-36.1667,-33.1326,-30.0985,-27.0644,-24.0603,-21.6494,-19.8806,-18.2239,-16.5672,-14.9105,-13.2537,-11.597,-9.9403]}}
    ' fairbeam-data: {"mesh_lines":{"x":[-8.2836,-6.6269,-4.9702,-3.3134,-1.6567,0,1.6567,3.3134,4.9702,6.6269,8.2836,9.9403,11.597,13.2537,14.9105,16.5672,18.2239,19.8806,21.6494,24.0603,27.0644,30.0985,33.1326,36.1667,39.2009,42.235,45.243,47.6667,49.4448,51.1103,53.0647,55.7978,59.0842,62.3732,65.6622,68.9512,72.2402,75.5291,78.8181,82.1071]}}
    ' fairbeam-data: {"mesh_lines":{"x":[85.3961,88.6851,91.9741,95.2631,98.5521,101.8411,105.1301,108.4191,111.7081,114.9971,118.2861]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-118.2861,-114.9971,-111.7081,-108.4191,-105.1301,-101.8411,-98.5521,-95.2631,-91.9741,-88.6851,-85.3961,-82.1071,-78.8181,-75.5291,-72.2402,-68.9512,-65.6622,-62.3732,-59.0842,-55.7978,-53.0647,-51.1103,-49.4448,-47.6667,-45.243,-42.235,-39.2009,-36.1667,-33.1326,-30.0985,-27.0644,-24.0603,-21.6494,-19.8806,-18.2239,-16.5672,-14.9105,-13.2537,-11.597,-9.9403]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-8.2836,-6.6269,-4.9702,-3.3134,-1.6567,0,1.6567,3.3134,4.9702,6.6269,8.2836,9.9403,11.597,13.2537,14.9105,16.5672,18.2239,19.8806,21.6494,24.0603,27.0644,30.0985,33.1326,36.1667,39.2009,42.235,45.243,47.6667,49.4448,51.1103,53.0647,55.7978,59.0842,62.3732,65.6622,68.9512,72.2402,75.5291,78.8181,82.1071]}}
    ' fairbeam-data: {"mesh_lines":{"y":[85.3961,88.6851,91.9741,95.2631,98.5521,101.8411,105.1301,108.4191,111.7081,114.9971,118.2861]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-68.2861,-64.9713,-61.6565,-58.3418,-55.027,-51.7123,-48.3975,-45.0828,-41.768,-38.4533,-35.1385,-31.8238,-28.509,-25.1942,-21.8795,-18.5647,-15.25,-11.9352,-8.6205,-5.3057,-2.233,0,1.6762,3,4.6547,6.3093,7.964,9.6187,11.2734,12.928,14.5827,16.2374,17.892,19.5467,21.2014,22.8561,24.5107,26.1654,27.8201,29.4747]}}
    ' fairbeam-data: {"mesh_lines":{"z":[31.1294,32.7841,34.4388,36.0934,37.7481,39.4028,41.0574,42.7121,44.3668,46.0215,47.6761,49.3308,50.9855,52.6401,54.2948,55.9495,57.6042,59.2588,60.9135,62.5682,64.2228,65.8775,67.5322,69.1869,70.8415,72.4962,74.1509,75.8055,77.4602,79.1149,80.7696,82.4242,84.0789,85.7336,87.3882,89.0429,90.6976,92.3523,94.0069,95.6616]}}
    ' fairbeam-data: {"mesh_lines":{"z":[97.3163,98.9709,100.6256,102.2803,103.935,105.5896,107.2443,108.899,110.5536,112.2083,113.863,115.5177,117.1723,118.827,120.4817,122.1363,123.791,125.4457,127.1004,128.755,130.4097,132.0644,133.719,135.3737,137.0284,138.6831,140.3377,141.9924,143.6471,145.3017,146.9564,148.6111,150.2658,151.9204,153.5751,155.2298,156.8844,158.5391,160.1938,161.8485]}}
    ' fairbeam-data: {"mesh_lines":{"z":[163.5031,165.1578,166.8125,168.4671,170.1218,171.7765,173.4312,175.0858,176.7405,178.3952,180.0498,181.7045,183.3592,185.0139,186.6685,188.3232,189.9779,191.6325,193.2872,194.9419,196.5966,198.2512,199.9059,201.5606,203.2152,204.8699,206.7437,209.339,212.5188,215.7103,218.9017,222.0931,225.2845,228.476,231.6674,234.8588,238.0503,241.2417,244.4331,247.6245]}}
    ' fairbeam-data: {"mesh_lines":{"z":[250.816,254.0074,257.1988,260.3903,263.5817,266.7731,269.9645,273.156]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":30,"pad":41.63784138888889,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-50"", ""-50""" + vbLf
    sCommand = sCommand + "     .LineTo ""50"", ""-50""" + vbLf
    sCommand = sCommand + "     .LineTo ""50"", ""50""" + vbLf
    sCommand = sCommand + "     .LineTo ""-50"", ""50""" + vbLf
    sCommand = sCommand + "     .LineTo ""-50"", ""-50""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    ' helix: zero-radius curve exported as a CST curve wire (PEC), not a solid
    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""helix_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    sCommand = sCommand + "With Polygon3D" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""helix""" + vbLf
    sCommand = sCommand + "     .Curve ""helix_curve""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""3""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""3.801071""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""4.602142""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""5.403213""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""6.204284""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""7.005355""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""7.806427""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""8.607498""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""9.408569""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""10.20964""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""11.010711""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""11.811782""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""12.612853""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""13.413924""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""14.214995""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""15.016066""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""15.817137""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""16.618209""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""17.41928""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""18.220351""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""19.021422""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""19.822493""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""20.623564""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""21.424635""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""22.225706""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""23.026777""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""23.827848""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""24.62892""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""25.429991""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""26.231062""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""27.032133""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""27.833204""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""28.634275""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""29.435346""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""30.236417""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""31.037488""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""31.838559""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""32.63963""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""33.440702""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""34.241773""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""35.042844""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""35.843915""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""36.644986""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""37.446057""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""38.247128""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""39.048199""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""39.84927""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""40.650341""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""41.451412""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""42.252484""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""43.053555""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""43.854626""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""44.655697""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""45.456768""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""46.257839""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""47.05891""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""47.859981""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""48.661052""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""49.462123""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""50.263195""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""51.064266""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""51.865337""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""52.666408""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""53.467479""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""54.26855""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""55.069621""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""55.870692""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""56.671763""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""57.472834""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""58.273905""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""59.074977""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""59.876048""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""60.677119""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""61.47819""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""62.279261""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""63.080332""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""63.881403""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""64.682474""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""65.483545""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""66.284616""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""67.085687""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""67.886759""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""68.68783""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""69.488901""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""70.289972""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""71.091043""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""71.892114""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""72.693185""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""73.494256""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""74.295327""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""75.096398""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""75.89747""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""76.698541""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""77.499612""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""78.300683""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""79.101754""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""79.902825""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""80.703896""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""81.504967""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""82.306038""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""83.107109""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""83.90818""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""84.709252""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""85.510323""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""86.311394""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""87.112465""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""87.913536""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""88.714607""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""89.515678""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""90.316749""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""91.11782""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""91.918891""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""92.719962""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""93.521034""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""94.322105""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""95.123176""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""95.924247""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""96.725318""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""97.526389""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""98.32746""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""99.128531""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""99.929602""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""100.730673""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""101.531745""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""102.332816""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""103.133887""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""103.934958""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""104.736029""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""105.5371""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""106.338171""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""107.139242""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""107.940313""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""108.741384""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""109.542455""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""110.343527""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""111.144598""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""111.945669""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""112.74674""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""113.547811""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""114.348882""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""115.149953""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""115.951024""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""116.752095""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""117.553166""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""118.354237""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""119.155309""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""119.95638""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""120.757451""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""121.558522""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""122.359593""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""123.160664""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""123.961735""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""124.762806""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""125.563877""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""126.364948""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""127.16602""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""127.967091""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""128.768162""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""129.569233""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""130.370304""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""131.171375""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""131.972446""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""132.773517""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""133.574588""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""134.375659""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""135.17673""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""135.977802""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""136.778873""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""137.579944""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""138.381015""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""139.182086""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""139.983157""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""140.784228""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""141.585299""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""142.38637""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""143.187441""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""143.988512""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""144.789584""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""145.590655""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""146.391726""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""147.192797""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""147.993868""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""148.794939""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""149.59601""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""150.397081""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""151.198152""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""151.999223""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""152.800295""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""153.601366""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""154.402437""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""155.203508""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""156.004579""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""156.80565""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""157.606721""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""158.407792""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""159.208863""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""160.009934""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""160.811005""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""161.612077""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""162.413148""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""163.214219""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""164.01529""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""164.816361""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""165.617432""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""166.418503""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""167.219574""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""168.020645""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""168.821716""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""169.622787""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""170.423859""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""171.22493""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""172.026001""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""172.827072""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""173.628143""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""174.429214""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""175.230285""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""176.031356""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""3.452231"", ""176.832427""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""6.799567"", ""177.633498""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""9.940302"", ""178.43457""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""12.779006"", ""179.235641""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""15.229427"", ""180.036712""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""17.217109"", ""180.837783""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""18.681658"", ""181.638854""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""19.578574"", ""182.439925""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""19.880605"", ""183.240996""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""19.578574"", ""184.042067""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""18.681658"", ""184.843138""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""17.217109"", ""185.644209""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""15.229427"", ""186.44528""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""12.779006"", ""187.246352""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""9.940302"", ""188.047423""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""6.799567"", ""188.848494""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""3.452231"", ""189.649565""" + vbLf
    sCommand = sCommand + "     .Point ""-19.880605"", ""0"", ""190.450636""" + vbLf
    sCommand = sCommand + "     .Point ""-19.578574"", ""-3.452231"", ""191.251707""" + vbLf
    sCommand = sCommand + "     .Point ""-18.681658"", ""-6.799567"", ""192.052778""" + vbLf
    sCommand = sCommand + "     .Point ""-17.217109"", ""-9.940302"", ""192.853849""" + vbLf
    sCommand = sCommand + "     .Point ""-15.229427"", ""-12.779006"", ""193.65492""" + vbLf
    sCommand = sCommand + "     .Point ""-12.779006"", ""-15.229427"", ""194.455991""" + vbLf
    sCommand = sCommand + "     .Point ""-9.940302"", ""-17.217109"", ""195.257062""" + vbLf
    sCommand = sCommand + "     .Point ""-6.799567"", ""-18.681658"", ""196.058134""" + vbLf
    sCommand = sCommand + "     .Point ""-3.452231"", ""-19.578574"", ""196.859205""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-19.880605"", ""197.660276""" + vbLf
    sCommand = sCommand + "     .Point ""3.452231"", ""-19.578574"", ""198.461347""" + vbLf
    sCommand = sCommand + "     .Point ""6.799567"", ""-18.681658"", ""199.262418""" + vbLf
    sCommand = sCommand + "     .Point ""9.940302"", ""-17.217109"", ""200.063489""" + vbLf
    sCommand = sCommand + "     .Point ""12.779006"", ""-15.229427"", ""200.86456""" + vbLf
    sCommand = sCommand + "     .Point ""15.229427"", ""-12.779006"", ""201.665631""" + vbLf
    sCommand = sCommand + "     .Point ""17.217109"", ""-9.940302"", ""202.466702""" + vbLf
    sCommand = sCommand + "     .Point ""18.681658"", ""-6.799567"", ""203.267773""" + vbLf
    sCommand = sCommand + "     .Point ""19.578574"", ""-3.452231"", ""204.068845""" + vbLf
    sCommand = sCommand + "     .Point ""19.880605"", ""0"", ""204.869916""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With Wire" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""helix_wire""" + vbLf
    sCommand = sCommand + "     .Type ""Curvewire""" + vbLf
    sCommand = sCommand + "     .Curve ""helix_curve:helix""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .SolidWireModel ""False""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Termination ""natural""" + vbLf
    sCommand = sCommand + "     .Add" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define wire: fairbeam:helix_wire", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""120""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""19.88060483"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""19.88060483"", ""0"", ""3""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":120,"start":[19.880604830153928,0,0],"stop":[19.880604830153928,0,3],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.1)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.1""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.1)", sCommand

    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.4)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.4""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.4)", sCommand

    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.7)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.7""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.7)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
