' Inset-fed patch (FR4, 2.4 GHz)
' CST-compatible VBA macro generated by Fairbeam 0.1.0 from an openEMS project
' model: inset-patch   created: 2026-09-24T23:27:48+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=59, Y=67, Z=44.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""2"", ""3""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-106.1464,-101.4216,-96.6968,-91.972,-87.2472,-82.5224,-77.7976,-73.0728,-68.348,-63.6232,-58.8984,-54.1736,-49.4488,-44.7239,-39.9991,-35.2743,-31.5834,-28.7,-26.318,-23.936,-21.554,-19.172,-16.79,-15.494,-14.303,-12.0259,-9.6439,-7.2619,-5.7,-2.4979,-0.1159,2.2661,4.6481,7.0301,9.4121,11.7941,14.303,15.494,16.5581,18.9401]}}
    ' fairbeam-data: {"mesh_lines":{"x":[21.3222,23.7042,26.7,30.5017,35.4113,40.321,45.2306,50.1403,55.0499,59.9596,64.8692,69.7789,74.6885,79.5981,84.5078,89.4174,94.3271,99.2367,104.1464]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-108.4464,-103.7216,-98.9968,-94.272,-89.5472,-84.8224,-80.0976,-75.3728,-70.648,-65.9232,-61.1984,-56.4736,-51.7488,-47.0239,-42.2991,-37.5743,-33.8834,-31,-28.618,-26.236,-23.854,-21.472,-19.794,-18.603,-16.708,-14.3259,-11.9439,-9.5619,-7.1799,-4.7979,-2.54,-1.54,-0.77,0,0.77,1.54,2.54,4.7301,7.1121,9.4941]}}
    ' fairbeam-data: {"mesh_lines":{"y":[11.8761,14.2581,16.6401,18.603,19.794,21.4042,23.7862,26.1682,28.5502,31,33.9344,37.6558,42.3752,47.0946,51.8139,56.5333,61.2527,65.9721,70.6914,75.4108,80.1302,84.8495,89.5689,94.2883,99.0076,103.727,108.4464]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-77.4464,-72.6849,-67.9234,-63.1619,-58.4004,-53.6389,-48.8774,-44.1159,-39.3544,-34.5929,-29.8314,-25.0699,-20.3084,-15.5469,-10.7854,-7.3265,-4.8139,-2.9887,-1.6628,-0.6997,0,0.5333,1.0667,1.6,2.2997,3.2628,4.5887,6.4139,8.9265,12.3854,17.1469,21.9084,26.6699,31.4314,36.1929,40.9544,45.7159,50.4774,55.2389,60.0004]}}
    ' fairbeam-data: {"mesh_lines":{"z":[64.7619,69.5234,74.2849,79.0464]}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.02 at 2.4 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""4.4""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.01174958459""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-28.7"", ""26.7""" + vbLf
    sCommand = sCommand + "     .Yrange ""-31"", ""31""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""1.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-28.7"", ""-31""" + vbLf
    sCommand = sCommand + "     .LineTo ""26.7"", ""-31""" + vbLf
    sCommand = sCommand + "     .LineTo ""26.7"", ""31""" + vbLf
    sCommand = sCommand + "     .LineTo ""-28.7"", ""31""" + vbLf
    sCommand = sCommand + "     .LineTo ""-28.7"", ""-31""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patch_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.6""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_1""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-5.7"", ""-19""" + vbLf
    sCommand = sCommand + "     .LineTo ""14.7"", ""-19""" + vbLf
    sCommand = sCommand + "     .LineTo ""14.7"", ""19""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""19""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""-19""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_1_curve:patch_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patch_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patch_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.6""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_2""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-14.7"", ""2.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""2.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""19""" + vbLf
    sCommand = sCommand + "     .LineTo ""-14.7"", ""19""" + vbLf
    sCommand = sCommand + "     .LineTo ""-14.7"", ""2.54""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_2_curve:patch_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patch_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patch_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.6""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_3""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-14.7"", ""-19""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""-19""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""-2.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-14.7"", ""-2.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-14.7"", ""-19""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_3_curve:patch_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patch_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patch_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.6""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_4""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-28.7"", ""-1.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""-1.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.7"", ""1.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-28.7"", ""1.54""" + vbLf
    sCommand = sCommand + "     .LineTo ""-28.7"", ""-1.54""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_4_curve:patch_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patch_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:patch_1"", ""fairbeam:patch_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:patch_1"", ""fairbeam:patch_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:patch_1"", ""fairbeam:patch_4""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:patch_1 (+3)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:patch_1"", ""patch""" + vbLf
    AddToHistory "rename block: fairbeam:patch_1 to: fairbeam:patch", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-28.7"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-28.7"", ""0"", ""1.6""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-28.7,-1.54,0],"stop":[-28.7,1.54,1.6],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.4013)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.4013""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.4013)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
