' Stepped-impedance low-pass filter
' CST-compatible VBA macro generated by Fairbeam 0.7.2 from an openEMS project
' model: lowpass-stepped   created: 2026-09-25T21:20:36+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=71, Y=51, Z=37.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.2"", ""6""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"MUR","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-42.0789,-39.8917,-37.7045,-35.5173,-33.3307,-31.4646,-30.0789,-28.789,-27.4991,-26.2093,-24.9194,-23.6295,-22.3441,-21.293,-20.5319,-19.8524,-19.1255,-18.1343,-16.9047,-15.6648,-14.4352,-13.4439,-12.717,-12.0376,-11.3064,-10.3078,-9.0711,-7.8343,-6.8357,-6.1045,-5.4251,-4.6985,-3.7078,-2.4788,-1.2394,0,1.2394,2.4788,3.7078,4.6985]}}
    ' fairbeam-data: {"mesh_lines":{"x":[5.4251,6.1045,6.8357,7.8343,9.0711,10.3078,11.3064,12.0376,12.717,13.4439,14.4352,15.6648,16.9047,18.1343,19.1255,19.8524,20.5319,21.293,22.3441,23.6295,24.9194,26.2093,27.4991,28.789,30.0789,31.4646,33.3307,35.5173,37.7045,39.8917,42.0789]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-21.2874,-19.1002,-16.913,-14.7257,-12.5392,-10.6731,-9.2874,-8.0236,-6.7598,-5.5032,-4.4836,-3.7403,-3.0609,-2.418,-1.8793,-1.4762,-1.1746,-0.949,-0.7462,-0.5913,-0.4745,-0.3659,-0.2657,-0.1876,-0.0938,0,0.0938,0.1876,0.2657,0.3659,0.4745,0.5913,0.7462,0.949,1.1746,1.4762,1.8793,2.418,3.0609,3.7403]}}
    ' fairbeam-data: {"mesh_lines":{"y":[4.4836,5.5032,6.7598,8.0236,9.2874,10.6731,12.5392,14.7257,16.913,19.1002,21.2874]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-12,-9.5583,-7.1165,-4.999,-3.4791,-2.389,-1.607,-1.0462,-0.644,-0.3554,-0.1484,0,0.1139,0.2032,0.2998,0.4065,0.5065,0.6098,0.7201,0.813,0.9068,1.0006,1.0788,1.1792,1.2875,1.4038,1.5579,1.762,2.0274,2.3969,2.9118,3.629,4.628,6.0197,7.9583,10.3776,12.813]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":20,"pad":12,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":4}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.0027 at 2.5 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""3.38""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.001269255551""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-30.078901"", ""30.078901""" + vbLf
    sCommand = sCommand + "     .Yrange ""-9.287382"", ""9.287382""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-30.078901"", ""-9.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""30.078901"", ""-9.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""30.078901"", ""9.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-30.078901"", ""9.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-30.078901"", ""-9.287382""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_1""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-30.078901"", ""-0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.078901"", ""-0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.078901"", ""0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""-30.078901"", ""0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""-30.078901"", ""-0.948953""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_1_curve:filter_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_2""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-20.078901"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-12.490557"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-12.490557"", ""3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.078901"", ""3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20.078901"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_2_curve:filter_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_3""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-12.490557"", ""-0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.651552"", ""-0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.651552"", ""0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""-12.490557"", ""0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""-12.490557"", ""-0.187566""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_3_curve:filter_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_4""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-5.651552"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""5.651552"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""5.651552"", ""3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.651552"", ""3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5.651552"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_4_curve:filter_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_5_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_5""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_5_curve""" + vbLf
    sCommand = sCommand + "     .Point ""5.651552"", ""-0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.490557"", ""-0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.490557"", ""0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""5.651552"", ""0.187566""" + vbLf
    sCommand = sCommand + "     .LineTo ""5.651552"", ""-0.187566""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_5_curve:filter_5""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_6_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_6""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_6_curve""" + vbLf
    sCommand = sCommand + "     .Point ""12.490557"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.078901"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.078901"", ""3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.490557"", ""3.287382""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.490557"", ""-3.287382""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_6_curve:filter_6""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""filter_7_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_7""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_7_curve""" + vbLf
    sCommand = sCommand + "     .Point ""20.078901"", ""-0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""30.078901"", ""-0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""30.078901"", ""0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.078901"", ""0.948953""" + vbLf
    sCommand = sCommand + "     .LineTo ""20.078901"", ""-0.948953""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""filter_7""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""filter_7_curve:filter_7""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:filter_7", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:filter_1"", ""fairbeam:filter_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:filter_1"", ""fairbeam:filter_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:filter_1"", ""fairbeam:filter_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:filter_1"", ""fairbeam:filter_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:filter_1"", ""fairbeam:filter_6""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:filter_1"", ""fairbeam:filter_7""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:filter_1 (+6)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:filter_1"", ""filter""" + vbLf
    AddToHistory "rename block: fairbeam:filter_1 to: fairbeam:filter", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port; P1/P2 lie on the port axis)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-30.07890106"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-30.07890106"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-30.0789010558814,-0.9489525602862942,0],"stop":[-30.0789010558814,0.9489525602862942,0.813],"direction":"z"}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""2""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""30.07890106"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""30.07890106"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 2", sCommand

    ' fairbeam-data: {"port":2,"type":"lumped","R":50,"start":[30.0789010558814,-0.9489525602862942,0],"stop":[30.0789010558814,0.9489525602862942,0.813],"direction":"z","excite":false}
    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

    ' WARNING: port 1: finite-width source exported as an axial line; transverse size is not preserved. Recheck the feed model.
    ' WARNING: port 2: finite-width source exported as an axial line; transverse size is not preserved. Recheck the feed model.
End Sub
