' Printed meander dipole (867 MHz)
' CST-compatible VBA macro generated by Fairbeam 0.5.6 from an openEMS project
' model: meander-dipole-867   created: 2026-10-03T17:57:50+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=94, Y=54, Z=197.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.75"", ""1""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-242.8478,-228.2875,-213.7271,-199.1668,-184.6065,-170.0461,-155.4858,-140.9255,-126.3651,-111.8048,-97.2445,-82.6841,-68.1238,-53.6277,-41.8777,-33.4321,-27.3628,-23,-19.6303,-17,-14.2128,-12.1798,-10.7214,-9.6752,-8.9246,-8.3862,-8,-7.6667,-7.3333,-7,-6.6667,-6.3333,-6,-5.7205,-5.3612,-5,-4.6172,-4.1117,-3.5,-2.8883]}}
    ' fairbeam-data: {"mesh_lines":{"x":[-2.3828,-2,-1.6388,-1.2795,-1,-0.6667,-0.3333,0,0.3333,0.6667,1,1.2795,1.6388,2,2.3828,2.8883,3.5,4.1117,4.6172,5,5.3612,5.7205,6,6.3333,6.6667,7,7.3333,7.6667,8,8.3171,8.7368,9.2922,10.0272,11,12.2782,14.0535,16.5298,19.9986,24.8384,31.6007]}}
    ' fairbeam-data: {"mesh_lines":{"x":[41.0432,54.1677,68.891,83.6143,98.3377,113.061,127.7844,142.5077,157.2311,171.9544,186.6778,201.4011,216.1245,230.8478]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-219.8478,-205.4732,-191.0986,-176.724,-162.3494,-147.9748,-133.6002,-119.2256,-104.851,-90.4764,-76.1018,-61.7272,-47.3526,-34.1992,-24.5985,-17.6672,-12.6665,-9.0583,-6.4558,-4.5737,-3.2252,-2.2454,-1.5551,-1.0563,-0.6667,-0.3333,0,0.4,0.8,1.2,1.6,2.0658,2.6855,3.5799,4.8096,6.5315,8.9429,12.3029,16.9889,23.5297]}}
    ' fairbeam-data: {"mesh_lines":{"y":[32.6531,45.3697,60.0429,74.7161,89.3893,104.0624,118.7356,133.4088,148.0819,162.7551,177.4283,192.1015,206.7746,221.4478]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-273.3478,-258.9705,-244.5931,-230.2158,-215.8385,-201.4612,-187.0838,-172.7065,-158.3292,-143.9519,-129.5745,-115.1972,-100.8199,-87.0205,-76.6312,-69.1352,-63.725,-59.8211,-57.0042,-54.9729,-53.5,-52.3472,-51.5199,-50.9261,-50.5,-50.1727,-49.9167,-49.6433,-49.3333,-49,-48.6667,-48.3333,-48,-47.6667,-47.3333,-47,-46.6667,-46.3333,-46,-45.6667]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-45.3333,-45,-44.6667,-44.3333,-44,-43.6667,-43.3333,-43,-42.6667,-42.3333,-42,-41.6667,-41.3333,-41,-40.6667,-40.3333,-40,-39.6667,-39.3333,-39,-38.6667,-38.3333,-38,-37.6667,-37.3333,-37,-36.6667,-36.3333,-36,-35.6667,-35.3333,-35,-34.6667,-34.3333,-34,-33.6667,-33.3333,-33,-32.6667,-32.3333]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-32,-31.6667,-31.3333,-31,-30.6185,-30.0886,-29.3523,-28.3293,-26.908,-24.9335,-22.1901,-18.3787,-13.2819,-9.0161,-5.9457,-3.7358,-2.1451,-1,0,1,2.1451,3.7358,5.9457,9.0161,13.2819,18.3787,22.1901,24.9335,26.908,28.3293,29.3523,30.0886,30.6185,31,31.3333,31.6667,32,32.3333,32.6667,33]}}
    ' fairbeam-data: {"mesh_lines":{"z":[33.3333,33.6667,34,34.3333,34.6667,35,35.3333,35.6667,36,36.3333,36.6667,37,37.3333,37.6667,38,38.3333,38.6667,39,39.3333,39.6667,40,40.3333,40.6667,41,41.3333,41.6667,42,42.3333,42.6667,43,43.3333,43.6667,44,44.3333,44.6667,45,45.3333,45.6667,46,46.3333]}}
    ' fairbeam-data: {"mesh_lines":{"z":[46.6667,47,47.3333,47.6667,48,48.3333,48.6667,49,49.3333,49.6433,49.9167,50.1727,50.5,50.9261,51.5199,52.3472,53.5,54.9729,57.0042,59.8211,63.725,69.1352,76.6312,87.0205,100.8199,115.1972,129.5745,143.9519,158.3292,172.7065,187.0838,201.4612,215.8385,230.2158,244.5931,258.9705,273.3478]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":20,"pad":99.93081933333333,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' board: equivalent tan d = 0.02 at 0.867 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""4.3""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.004148070674""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: board", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""board_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board_1""" + vbLf
    sCommand = sCommand + "     .Curve ""board_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-53.5"", ""-23""" + vbLf
    sCommand = sCommand + "     .LineTo ""-53.5"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""0"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""0"", ""-17""" + vbLf
    sCommand = sCommand + "     .LineTo ""-53.5"", ""-23""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With ExtrudeCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""board""" + vbLf
    sCommand = sCommand + "     .Thickness ""1.6""" + vbLf
    sCommand = sCommand + "     .Twistangle ""0""" + vbLf
    sCommand = sCommand + "     .Taperangle ""0""" + vbLf
    sCommand = sCommand + "     .DeleteProfile ""True""" + vbLf
    sCommand = sCommand + "     .Curve ""board_1_curve:board_1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define extrusion: fairbeam:board_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""board_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board_2""" + vbLf
    sCommand = sCommand + "     .Curve ""board_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""0"", ""-17""" + vbLf
    sCommand = sCommand + "     .LineTo ""0"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""53.5"", ""11""" + vbLf
    sCommand = sCommand + "     .LineTo ""53.5"", ""-11""" + vbLf
    sCommand = sCommand + "     .LineTo ""0"", ""-17""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With ExtrudeCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""board""" + vbLf
    sCommand = sCommand + "     .Thickness ""1.6""" + vbLf
    sCommand = sCommand + "     .Twistangle ""0""" + vbLf
    sCommand = sCommand + "     .Taperangle ""0""" + vbLf
    sCommand = sCommand + "     .DeleteProfile ""True""" + vbLf
    sCommand = sCommand + "     .Curve ""board_2_curve:board_2""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define extrusion: fairbeam:board_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:board_1"", ""fairbeam:board_2""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:board_1 (+1)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:board_1"", ""board""" + vbLf
    AddToHistory "rename block: fairbeam:board_1 to: fairbeam:board", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-1"", ""1""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""1"", ""31""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_1", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-1"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""31"", ""33""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_2", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""1""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""47"", ""49""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_3", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-1"", ""1""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""47"", ""50.5""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_4", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-1"", ""1""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-31"", ""-1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_5", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-1"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-33"", ""-31""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_6", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_7""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""1""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-49"", ""-47""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_7", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_feed_and_tip_8""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-1"", ""1""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-50.5"", ""-47""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_feed_and_tip_8", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_6""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_7""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_feed_and_tip_1"", ""fairbeam:arm_feed_and_tip_8""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:arm_feed_and_tip_1 (+7)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:arm_feed_and_tip_1"", ""arm_feed_and_tip""" + vbLf
    AddToHistory "rename block: fairbeam:arm_feed_and_tip_1 to: fairbeam:arm_feed_and_tip", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_rungs_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""35"", ""37""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_rungs_1", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_rungs_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""39"", ""41""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_rungs_2", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_rungs_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""43"", ""45""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_rungs_3", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_rungs_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-37"", ""-35""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_rungs_4", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_rungs_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-41"", ""-39""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_rungs_5", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_rungs_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-45"", ""-43""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_rungs_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_rungs_1"", ""fairbeam:arm_rungs_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_rungs_1"", ""fairbeam:arm_rungs_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_rungs_1"", ""fairbeam:arm_rungs_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_rungs_1"", ""fairbeam:arm_rungs_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_rungs_1"", ""fairbeam:arm_rungs_6""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:arm_rungs_1 (+5)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:arm_rungs_1"", ""arm_rungs""" + vbLf
    AddToHistory "rename block: fairbeam:arm_rungs_1 to: fairbeam:arm_rungs", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_aft_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""6"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""33"", ""35""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_aft_1", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_aft_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""6"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""41"", ""43""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_aft_2", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_aft_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""6"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-35"", ""-33""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_aft_3", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_aft_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""6"", ""8""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-43"", ""-41""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_aft_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_links_aft_1"", ""fairbeam:arm_links_aft_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_links_aft_1"", ""fairbeam:arm_links_aft_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_links_aft_1"", ""fairbeam:arm_links_aft_4""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:arm_links_aft_1 (+3)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:arm_links_aft_1"", ""arm_links_aft""" + vbLf
    AddToHistory "rename block: fairbeam:arm_links_aft_1 to: fairbeam:arm_links_aft", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_fwd_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""-6""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""37"", ""39""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_fwd_1", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_fwd_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""-6""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""45"", ""47""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_fwd_2", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_fwd_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""-6""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-39"", ""-37""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_fwd_3", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""arm_links_fwd_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-8"", ""-6""" + vbLf
    sCommand = sCommand + "     .Yrange ""-0.035"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-47"", ""-45""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:arm_links_fwd_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_links_fwd_1"", ""fairbeam:arm_links_fwd_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_links_fwd_1"", ""fairbeam:arm_links_fwd_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:arm_links_fwd_1"", ""fairbeam:arm_links_fwd_4""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:arm_links_fwd_1 (+3)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:arm_links_fwd_1"", ""arm_links_fwd""" + vbLf
    AddToHistory "rename block: fairbeam:arm_links_fwd_1 to: fairbeam:arm_links_fwd", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""0"", ""0"", ""-1""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-1,0,-1],"stop":[1,0,1],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=0.867)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""0.867""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=0.867)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-50""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
