' Microstrip line (50 ohm, two-port)
' CST-compatible VBA macro generated by Fairbeam 0.7.2 from an openEMS project
' model: microstrip-line   created: 2026-09-25T00:15:02+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=41, Y=41, Z=32.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.5"", ""6""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"MUR","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-28.13,-25.7956,-23.4611,-21.5555,-20,-18.6411,-17.2822,-15.9234,-14.5645,-13.2056,-11.8467,-10.4878,-9.129,-7.7701,-6.4112,-5.0523,-3.6934,-2.3346,-0.9757,0.3832,1.7421,3.101,4.4598,5.8187,7.1776,8.5365,9.8954,11.2542,12.6131,13.972,15.3309,16.6898,18.0486,19.4075,20,20.6373,21.4659,22.543,23.9433,25.7636]}}
    ' fairbeam-data: {"mesh_lines":{"x":[28.13]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-18.13,-16.0975,-14.065,-12.0325,-10,-7.8265,-6.1546,-4.8686,-3.8793,-3.1183,-2.5329,-2.0826,-1.7362,-1.4698,-1.2648,-1.1072,-0.949,-0.7118,-0.4745,-0.2372,0,0.2373,0.4745,0.7118,0.949,1.1072,1.2648,1.4698,1.7362,2.0826,2.5329,3.1183,3.8793,4.8686,6.1546,7.8265,10,12.0325,14.065,16.0975]}}
    ' fairbeam-data: {"mesh_lines":{"y":[18.13]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-4.065,-3.0293,-2.2325,-1.6197,-1.1482,-0.7856,-0.5066,-0.292,-0.127,0,0.1016,0.2032,0.3049,0.4065,0.5081,0.6098,0.7114,0.813,0.9379,1.1003,1.3114,1.5859,1.9426,2.4064,3.0094,3.7932,4.8122,6.1369,7.859,10.0977,11.5528,13.008]}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.0027 at 3.25 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""3.38""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.001650032217""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-20"", ""20""" + vbLf
    sCommand = sCommand + "     .Yrange ""-10"", ""10""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-20"", ""-10""" + vbLf
    sCommand = sCommand + "     .LineTo ""20"", ""-10""" + vbLf
    sCommand = sCommand + "     .LineTo ""20"", ""10""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20"", ""10""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20"", ""-10""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strip_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strip""" + vbLf
    sCommand = sCommand + "     .Curve ""strip_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-20"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""20"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""20"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""-20"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strip""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strip_curve:strip""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strip", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port; P1/P2 lie on the port axis)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-20"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-20"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-20,-0.949,0],"stop":[-20,0.949,0.813],"direction":"z"}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""2""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""20"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""20"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 2", sCommand

    ' fairbeam-data: {"port":2,"type":"lumped","R":50,"start":[20,-0.949,0],"stop":[20,0.949,0.813],"direction":"z","excite":false}
    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

    ' WARNING: port 1: finite-width source exported as an axial line; transverse size is not preserved. Recheck the feed model.
    ' WARNING: port 2: finite-width source exported as an axial line; transverse size is not preserved. Recheck the feed model.
End Sub
