' Minkowski fractal patch
' CST-compatible VBA macro generated by Fairbeam 0.1.0 from an openEMS project
' model: minkowski-patch   created: 2026-09-24T23:33:20+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=62, Y=62, Z=32.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""1.6"", ""3.2""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"MUR","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-76.8426,-72.4801,-68.1175,-63.755,-59.3925,-55.03,-50.6675,-46.305,-41.9425,-37.5799,-33.2174,-30,-27.4521,-24.9042,-22.3563,-19.8084,-17,-15.75,-15,-13.25,-12,-10.75,-10,-8.25,-7,-5.75,-5,-3.5,-2,-0.75,0,1.75,3,4.25,5,6.75,8,9.25,10,11.75]}}
    ' fairbeam-data: {"mesh_lines":{"x":[13,14.25,15,16.75,18.4101,20.958,23.5059,26.0538,28.6017,30,31.7697,34.164,37.4031,41.7853,46.1674,50.5496,54.9318,59.3139,63.6961,68.0782,72.4604,76.8426]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-76.8426,-72.4801,-68.1175,-63.755,-59.3925,-55.03,-50.6675,-46.305,-41.9425,-37.5799,-33.2174,-30,-27.4521,-24.9042,-22.3563,-19.8084,-17,-15.75,-15,-13.25,-12,-10.75,-10,-8.25,-7,-5.75,-5,-3.25,-2,-0.75,0,1.75,3,4.25,5,6.75,8,9.25,10,11.75]}}
    ' fairbeam-data: {"mesh_lines":{"y":[13,14.25,15,16.75,18.4101,20.958,23.5059,26.0538,28.6017,30,31.7697,34.164,37.4031,41.7853,46.1674,50.5496,54.9318,59.3139,63.6961,68.0782,72.4604,76.8426]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-46.8426,-42.2853,-37.728,-33.1708,-28.6135,-24.0562,-19.4989,-14.9417,-10.3844,-7.0664,-4.6506,-2.8917,-1.6112,-0.6788,0,0.508,1.016,1.524,2.2028,3.1352,4.4157,6.1746,8.5904,11.9084,16.4657,21.0229,25.5802,30.1375,34.6948,39.252,43.8093,48.3666]}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.0027 at 2.4 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""3.38""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.001218485329""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-30"", ""30""" + vbLf
    sCommand = sCommand + "     .Yrange ""-30"", ""30""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-30"", ""-30""" + vbLf
    sCommand = sCommand + "     .LineTo ""30"", ""-30""" + vbLf
    sCommand = sCommand + "     .LineTo ""30"", ""30""" + vbLf
    sCommand = sCommand + "     .LineTo ""-30"", ""30""" + vbLf
    sCommand = sCommand + "     .LineTo ""-30"", ""-30""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patch_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-15"", ""-15""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5"", ""-15""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5"", ""-10""" + vbLf
    sCommand = sCommand + "     .LineTo ""5"", ""-10""" + vbLf
    sCommand = sCommand + "     .LineTo ""5"", ""-15""" + vbLf
    sCommand = sCommand + "     .LineTo ""15"", ""-15""" + vbLf
    sCommand = sCommand + "     .LineTo ""15"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""10"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""10"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""15"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""15"", ""15""" + vbLf
    sCommand = sCommand + "     .LineTo ""5"", ""15""" + vbLf
    sCommand = sCommand + "     .LineTo ""5"", ""10""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5"", ""10""" + vbLf
    sCommand = sCommand + "     .LineTo ""-5"", ""15""" + vbLf
    sCommand = sCommand + "     .LineTo ""-15"", ""15""" + vbLf
    sCommand = sCommand + "     .LineTo ""-15"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-15"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""-15"", ""-15""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patch""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patch_curve:patch""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patch", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-3.5"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-3.5"", ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-3.5,0,0],"stop":[-3.5,0,1.524],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.324)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.324""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.324)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
