' Patch array 4 x 1
' CST-compatible VBA macro generated by Fairbeam 0.1.0 from an openEMS project
' model: patch-array-4x1   created: 2026-09-25T02:10:57+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=65, Y=142, Z=49.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""1.8"", ""3""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-114.6102,-109.6774,-104.7446,-99.8118,-94.879,-89.9462,-85.0134,-80.0806,-75.1478,-70.215,-65.2822,-60.3495,-55.4167,-50.4839,-45.5511,-40.6183,-36.1885,-33,-30.4803,-27.9606,-25.4408,-22.9211,-20.4168,-18.387,-16.9059,-15.547,-14.2688,-12.5817,-10.4364,-8.2182,-6,-3.4343,-0.8687,1.697,4.2627,6.8284,9.394,11.9493,14.0344,15.547]}}
    ' fairbeam-data: {"mesh_lines":{"x":[16.9059,18.387,20.4168,22.9211,25.4408,27.9606,30.4803,33,36.1885,40.6183,45.5511,50.4839,55.4167,60.3495,65.2822,70.215,75.1478,80.0806,85.0134,89.9462,94.879,99.8118,104.7446,109.6774,114.6102]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-203.4102,-198.4774,-193.5446,-188.6118,-183.679,-178.7462,-173.8134,-168.8806,-163.9478,-159.015,-154.0822,-149.1495,-144.2167,-139.2839,-134.3511,-129.4183,-124.9885,-121.8,-119.1405,-116.4841,-114.2836,-112.7059,-111.347,-109.7855,-107.6138,-104.9819,-102.3455,-99.7091,-97.0728,-94.4364,-91.8,-89.1636,-86.5272,-83.8909,-81.2545,-78.6181,-75.9862,-73.8145,-72.253,-70.8941]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-69.4283,-67.4251,-64.946,-62.4487,-59.9513,-57.454,-54.9749,-52.9717,-51.5059,-50.147,-48.5855,-46.4138,-43.7819,-41.1455,-38.5091,-35.8728,-33.2364,-30.6,-27.9636,-25.3272,-22.6909,-20.0545,-17.4181,-14.7862,-12.6145,-11.053,-9.6941,-8.2283,-6.2251,-3.746,-1.2487,1.2487,3.746,6.2251,8.2283,9.6941,11.053,12.6145,14.7862,17.4181]}}
    ' fairbeam-data: {"mesh_lines":{"y":[20.0545,22.6909,25.3272,27.9636,30.6,33.2364,35.8728,38.5091,41.1455,43.7819,46.4138,48.5855,50.147,51.5059,52.9717,54.9749,57.454,59.9513,62.4487,64.946,67.4251,69.4283,70.8941,72.253,73.8145,75.9862,78.6181,81.2545,83.8909,86.5272,89.1636,91.8,94.4364,97.0728,99.7091,102.3455,104.9819,107.6138,109.7855,111.347]}}
    ' fairbeam-data: {"mesh_lines":{"y":[112.7059,114.2836,116.4841,119.1405,121.8,124.9885,129.4183,134.3511,139.2839,144.2167,149.1495,154.0822,159.015,163.9478,168.8806,173.8134,178.7462,183.679,188.6118,193.5446,198.4774,203.4102]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-81.6102,-76.7966,-71.9831,-67.1695,-62.356,-57.5424,-52.7288,-47.9153,-43.1017,-38.2882,-33.4746,-28.6611,-23.8475,-19.034,-14.2204,-9.9467,-6.856,-4.6287,-3.0235,-1.8667,-1.033,-0.4336,0,0.381,0.762,1.143,1.524,1.9576,2.557,3.3907,4.5475,6.1527,8.38,11.4707,15.7444,20.558,25.3715,30.1851,34.9986,39.8122]}}
    ' fairbeam-data: {"mesh_lines":{"z":[44.6257,49.4393,54.2528,59.0664,63.88,68.6935,73.5071,78.3206,83.1342]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":20,"pad":41.63784138888889,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.001 at 2.45 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""3.38""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.0004606927557""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-33"", ""33""" + vbLf
    sCommand = sCommand + "     .Yrange ""-121.8"", ""121.8""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-33"", ""-121.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""33"", ""-121.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""33"", ""121.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-33"", ""121.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-33"", ""-121.8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patches_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_1""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-16"", ""-111.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""-111.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""-71.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""-71.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""-111.8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_1_curve:patches_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patches_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patches_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_2""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-16"", ""-50.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""-50.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""-10.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""-10.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""-50.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_2_curve:patches_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patches_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patches_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_3""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-16"", ""10.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""10.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""50.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""50.6""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""10.6""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_3_curve:patches_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patches_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""patches_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""1.524""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_4""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-16"", ""71.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""71.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""16"", ""111.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""111.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-16"", ""71.8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""patches_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""patches_4_curve:patches_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:patches_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:patches_1"", ""fairbeam:patches_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:patches_1"", ""fairbeam:patches_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:patches_1"", ""fairbeam:patches_4""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:patches_1 (+3)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:patches_1"", ""patches""" + vbLf
    AddToHistory "rename block: fairbeam:patches_1 to: fairbeam:patches", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-6"", ""-91.8"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-6"", ""-91.8"", ""1.524""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-6,-91.80000000000001,0],"stop":[-6,-91.80000000000001,1.524],"direction":"z"}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""2""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-6"", ""-30.6"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-6"", ""-30.6"", ""1.524""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 2", sCommand

    ' fairbeam-data: {"port":2,"type":"lumped","R":50,"start":[-6,-30.6,0],"stop":[-6,-30.6,1.524],"direction":"z","excite":false}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""3""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-6"", ""30.6"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-6"", ""30.6"", ""1.524""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 3", sCommand

    ' fairbeam-data: {"port":3,"type":"lumped","R":50,"start":[-6,30.6,0],"stop":[-6,30.6,1.524],"direction":"z","excite":false}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""4""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-6"", ""91.8"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-6"", ""91.8"", ""1.524""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 4", sCommand

    ' fairbeam-data: {"port":4,"type":"lumped","R":50,"start":[-6,91.80000000000001,0],"stop":[-6,91.80000000000001,1.524],"direction":"z","excite":false}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=2.4525)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""2.4525""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=2.4525)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
