' Pyramidal horn (WR-90, 10 GHz)
' CST-compatible VBA macro generated by Fairbeam 0.4.4 from an openEMS project
' model: pyramidal-horn   created: 2026-09-28T23:07:19+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=123, Y=105, Z=88.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

' Polyhedra (4) are imported from the .stl files written next to this macro.
' Set STL_FOLDER to the folder that holds them (end it with a backslash or not). Left empty, the macro
' looks in the folder of the current CST project (GetProjectPath("Root")) and, if the files are not
' there, asks for the folder.
Const STL_FOLDER As String = ""

Sub Main ()
    Dim sCommand As String
    Dim sStlDir As String
    ' fairbeam-helper: begin
    sStlDir = FairbeamStlFolder("pyramidal-horn_horn_5.stl")
    If sStlDir = "" Then
        MsgBox "The .stl files exported with this macro were not found. Put them in one folder and set STL_FOLDER at the top of the macro to it.", vbExclamation, "Fairbeam"
        Exit Sub
    End If
    ' fairbeam-helper: end

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""8"", ""12""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-64.474,-63.2627,-62.0514,-60.84,-59.6287,-58.4174,-57.2061,-55.9948,-54.7834,-53.5721,-52.3608,-51.1495,-49.9382,-48.7269,-47.5155,-46.3042,-45.1124,-44.1124,-43.1124,-41.9064,-40.6809,-39.4553,-38.2298,-37.0043,-35.7788,-34.5532,-33.3277,-32.1022,-30.8767,-29.6511,-28.4256,-27.2001,-25.9746,-24.749,-23.5235,-22.298,-21.0725,-19.847,-18.6214,-17.3959]}}
    ' fairbeam-data: {"mesh_lines":{"x":[-16.1704,-15.1156,-14.3598,-13.8182,-13.43,-13.0967,-12.7633,-12.43,-12.0967,-11.7633,-11.43,-11.0381,-10.4897,-9.7222,-8.6488,-7.4132,-6.1777,-4.9422,-3.7066,-2.4711,-1.2355,0,1.2355,2.4711,3.7066,4.9422,6.1777,7.4132,8.6488,9.7222,10.4897,11.0381,11.43,11.7633,12.0967,12.43,12.7633,13.0967,13.43,13.8182]}}
    ' fairbeam-data: {"mesh_lines":{"x":[14.3598,15.1156,16.1704,17.3959,18.6214,19.847,21.0725,22.298,23.5235,24.749,25.9746,27.2001,28.4256,29.6511,30.8767,32.1022,33.3277,34.5532,35.7788,37.0043,38.2298,39.4553,40.6809,41.9064,43.1124,44.1124,45.1124,46.3042,47.5155,48.7269,49.9382,51.1495,52.3608,53.5721,54.7834,55.9948,57.2061,58.4174,59.6287,60.84]}}
    ' fairbeam-data: {"mesh_lines":{"x":[62.0514,63.2627,64.474]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-53.6306,-52.4192,-51.2079,-49.9966,-48.7853,-47.574,-46.3626,-45.1513,-43.94,-42.7287,-41.5174,-40.3061,-39.0947,-37.8834,-36.6721,-35.4608,-34.269,-33.269,-32.269,-31.0444,-29.8003,-28.5563,-27.3122,-26.0681,-24.824,-23.5799,-22.3359,-21.0918,-19.8477,-18.6036,-17.3595,-16.1155,-14.8714,-13.6273,-12.3832,-11.1391,-9.8951,-8.8066,-8.029,-7.4752]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-7.08,-6.7467,-6.4133,-6.08,-5.7467,-5.4133,-5.08,-4.6988,-4.1695,-3.4343,-2.4133,-1.2067,0,1.2067,2.4133,3.4343,4.1695,4.6988,5.08,5.4133,5.7467,6.08,6.4133,6.7467,7.08,7.4752,8.029,8.8066,9.8951,11.1391,12.3832,13.6273,14.8714,16.1155,17.3595,18.6036,19.8477,21.0918,22.3359,23.5799]}}
    ' fairbeam-data: {"mesh_lines":{"y":[24.824,26.0681,27.3122,28.5563,29.8003,31.0444,32.269,33.269,34.269,35.4608,36.6721,37.8834,39.0947,40.3061,41.5174,42.7287,43.94,45.1513,46.3626,47.574,48.7853,49.9966,51.2079,52.4192,53.6306]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-30,-29.7918,-29.5502,-29.2136,-28.7442,-28.0896,-27.1767,-25.9849,-24.7633,-23.5418,-22.3202,-21.0987,-19.8771,-18.6556,-17.434,-16.2125,-15.0104,-14.0104,-13.0104,-11.8453,-10.6608,-9.4762,-8.2917,-7.1072,-5.9226,-4.7381,-3.5536,-2.3691,-1.1845,0,1.2341,2.4682,3.7024,4.9365,6.1706,7.4047,8.6388,9.8729,11.1071,12.3412]}}
    ' fairbeam-data: {"mesh_lines":{"z":[13.5753,14.8094,16.0435,17.2776,18.5118,19.7459,20.98,22.2141,23.4482,24.6824,25.9165,27.1506,28.3847,29.6188,30.8529,32.0871,33.3212,34.5553,35.7894,37.0235,38.2576,39.4918,40.7259,41.96,43.1941,44.4282,45.6624,46.8965,48.1306,49.3647,50.5988,51.8329,53.043,54.2531,55.4632,56.6733,57.8834,59.0935,60.3036,61.5137]}}
    ' fairbeam-data: {"mesh_lines":{"z":[62.7238,63.9339,65.144,66.3541,67.5642,68.7743,69.9844,71.1945]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":20,"pad":[9.368514312499999,9.368514312499999,9.368514312499999,9.368514312499999,0,9.368514312499999],"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""horn_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-13.43"", ""13.43""" + vbLf
    sCommand = sCommand + "     .Yrange ""-7.08"", ""-5.08""" + vbLf
    sCommand = sCommand + "     .Zrange ""-30"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:horn_1", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""horn_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-13.43"", ""13.43""" + vbLf
    sCommand = sCommand + "     .Yrange ""5.08"", ""7.08""" + vbLf
    sCommand = sCommand + "     .Zrange ""-30"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:horn_2", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""horn_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""-13.43"", ""-11.43""" + vbLf
    sCommand = sCommand + "     .Yrange ""-5.08"", ""5.08""" + vbLf
    sCommand = sCommand + "     .Zrange ""-30"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:horn_3", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""horn_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Xrange ""11.43"", ""13.43""" + vbLf
    sCommand = sCommand + "     .Yrange ""-5.08"", ""5.08""" + vbLf
    sCommand = sCommand + "     .Zrange ""-30"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:horn_4", sCommand

    ' horn: polyhedron (12 faces, 12 triangles) imported from pyramidal-horn_horn_5.stl
    sCommand = ""
    sCommand = sCommand + "With STL" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .FileName """ + sStlDir + "pyramidal-horn_horn_5.stl""" + vbLf
    sCommand = sCommand + "     .Id ""1""" + vbLf
    sCommand = sCommand + "     .Name ""horn_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .ScaleToUnit ""True""" + vbLf
    sCommand = sCommand + "     .ImportFileUnits ""mm""" + vbLf
    sCommand = sCommand + "     .ImportToActiveCoordinateSystem ""False""" + vbLf
    sCommand = sCommand + "     .Read" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "import polyhedron: fairbeam:horn_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.ChangeMaterial ""fairbeam:horn_5"", ""PEC""" + vbLf
    AddToHistory "change material: fairbeam:horn_5", sCommand

    ' horn: polyhedron (12 faces, 12 triangles) imported from pyramidal-horn_horn_6.stl
    sCommand = ""
    sCommand = sCommand + "With STL" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .FileName """ + sStlDir + "pyramidal-horn_horn_6.stl""" + vbLf
    sCommand = sCommand + "     .Id ""2""" + vbLf
    sCommand = sCommand + "     .Name ""horn_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .ScaleToUnit ""True""" + vbLf
    sCommand = sCommand + "     .ImportFileUnits ""mm""" + vbLf
    sCommand = sCommand + "     .ImportToActiveCoordinateSystem ""False""" + vbLf
    sCommand = sCommand + "     .Read" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "import polyhedron: fairbeam:horn_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.ChangeMaterial ""fairbeam:horn_6"", ""PEC""" + vbLf
    AddToHistory "change material: fairbeam:horn_6", sCommand

    ' horn: polyhedron (12 faces, 12 triangles) imported from pyramidal-horn_horn_7.stl
    sCommand = ""
    sCommand = sCommand + "With STL" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .FileName """ + sStlDir + "pyramidal-horn_horn_7.stl""" + vbLf
    sCommand = sCommand + "     .Id ""3""" + vbLf
    sCommand = sCommand + "     .Name ""horn_7""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .ScaleToUnit ""True""" + vbLf
    sCommand = sCommand + "     .ImportFileUnits ""mm""" + vbLf
    sCommand = sCommand + "     .ImportToActiveCoordinateSystem ""False""" + vbLf
    sCommand = sCommand + "     .Read" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "import polyhedron: fairbeam:horn_7", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.ChangeMaterial ""fairbeam:horn_7"", ""PEC""" + vbLf
    AddToHistory "change material: fairbeam:horn_7", sCommand

    ' horn: polyhedron (12 faces, 12 triangles) imported from pyramidal-horn_horn_8.stl
    sCommand = ""
    sCommand = sCommand + "With STL" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .FileName """ + sStlDir + "pyramidal-horn_horn_8.stl""" + vbLf
    sCommand = sCommand + "     .Id ""4""" + vbLf
    sCommand = sCommand + "     .Name ""horn_8""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .ScaleToUnit ""True""" + vbLf
    sCommand = sCommand + "     .ImportFileUnits ""mm""" + vbLf
    sCommand = sCommand + "     .ImportToActiveCoordinateSystem ""False""" + vbLf
    sCommand = sCommand + "     .Read" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "import polyhedron: fairbeam:horn_8", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.ChangeMaterial ""fairbeam:horn_8"", ""PEC""" + vbLf
    AddToHistory "change material: fairbeam:horn_8", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_6""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_7""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:horn_1"", ""fairbeam:horn_8""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:horn_1 (+7)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:horn_1"", ""horn""" + vbLf
    AddToHistory "rename block: fairbeam:horn_1 to: fairbeam:horn", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    ' fairbeam-data: {"port":1,"type":"waveguide","mode":"TE10","a":22.86,"b":10.16,"start":[-11.43,-5.08,-15.010377100000001],"stop":[11.43,5.08,-13.010377100000001],"direction":"z"}
    sCommand = ""
    sCommand = sCommand + "With Port" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .NumberOfModes ""1""" + vbLf
    sCommand = sCommand + "     .Orientation ""zmin""" + vbLf
    sCommand = sCommand + "     .Coordinates ""Free""" + vbLf
    sCommand = sCommand + "     .Xrange ""-11.43"", ""11.43""" + vbLf
    sCommand = sCommand + "     .Yrange ""-5.08"", ""5.08""" + vbLf
    sCommand = sCommand + "     .Zrange ""-15.0103771"", ""-15.0103771""" + vbLf
    sCommand = sCommand + "     .PortOnBound ""False""" + vbLf
    sCommand = sCommand + "     .ClipPickedPortToBound ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define waveguide port: 1", sCommand

    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=8)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""8""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=8)", sCommand

    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=10)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""10""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=10)", sCommand

    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=12)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""12""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=12)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub

' fairbeam-helper: begin
' Folder of the companion .stl files, with a trailing backslash; empty if sProbe is not found in it.
Function FairbeamStlFolder(sProbe As String) As String
    Dim sDir As String
    sDir = STL_FOLDER
    If sDir = "" Then sDir = GetProjectPath("Root")
    If sDir <> "" And Right(sDir, 1) <> "\" Then sDir = sDir + "\"
    If sDir = "" Or Dir(sDir + sProbe) = "" Then
        sDir = InputBox("Folder with the .stl files that belong to this macro:", "Fairbeam", sDir)
        If sDir <> "" And Right(sDir, 1) <> "\" Then sDir = sDir + "\"
    End If
    If Dir(sDir + sProbe) = "" Then sDir = ""
    FairbeamStlFolder = sDir
End Function
' fairbeam-helper: end
