' Sierpinski gasket monopole - iterations=0
' CST-compatible VBA macro generated by Fairbeam 0.7.2 from an openEMS project
' model: sierpinski-monopole   created: 2026-09-24T22:36:46+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=154, Y=113, Z=108.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.5"", ""8""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""1""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"PEC","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-100,-98.1498,-96.2997,-94.4495,-92.5994,-90.7492,-88.8991,-87.0489,-85.1988,-83.3486,-81.4985,-79.6483,-77.7982,-75.948,-74.0979,-72.2477,-70.3976,-68.5474,-66.6973,-64.8471,-62.997,-61.1468,-59.2967,-57.4465,-55.5964,-53.7462,-51.8961,-50.0459,-48.1958,-46.3456,-44.4955,-42.6453,-40.7951,-38.945,-37.0948,-35.2447,-33.3945,-31.899,-30.69,-29.7128]}}
    ' fairbeam-data: {"mesh_lines":{"x":[-28.9128,-28.1128,-27.7128,-27.3128,-26.5128,-25.7128,-24.9128,-24.1128,-23.3128,-22.5128,-21.7128,-20.9128,-20.1128,-19.3128,-18.5128,-17.7128,-16.9128,-16.1128,-15.3128,-14.5128,-13.7128,-12.9128,-12.1128,-11.3128,-10.5128,-9.7128,-8.9128,-8.1128,-7.3128,-6.5128,-5.7128,-4.9128,-4.1128,-3.3128,-2.5128,-1.7128,-0.9128,0,0.6872,1.4872]}}
    ' fairbeam-data: {"mesh_lines":{"x":[2.2872,3.0872,3.8872,4.6872,5.4872,6.2872,7.0872,7.8872,8.6872,9.4872,10.2872,11.0872,11.8872,12.6872,13.4872,14.2872,15.0872,15.8872,16.6872,17.4872,18.2872,19.0872,19.8872,20.6872,21.4872,22.2872,23.0872,23.8872,24.6872,25.4872,26.2872,27.0872,27.7128,28.6872,29.4872,30.4676,31.6804,33.1807,35.0368,36.8929]}}
    ' fairbeam-data: {"mesh_lines":{"x":[38.749,40.6051,42.4612,44.3173,46.1734,48.0295,49.8856,51.7416,53.5977,55.4538,57.3099,59.166,61.0221,62.8782,64.7343,66.5904,68.4465,70.3025,72.1586,74.0147,75.8708,77.7269,79.583,81.4391,83.2952,85.1513,87.0074,88.8635,90.7195,92.5756,94.4317,96.2878,98.1439,100]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-100,-98.143,-96.2861,-94.4291,-92.5722,-90.7152,-88.8583,-87.0013,-85.1444,-83.2874,-81.4304,-79.5735,-77.7165,-75.8596,-74.0026,-72.1457,-70.2887,-68.4318,-66.5748,-64.7178,-62.8609,-61.0039,-59.147,-57.29,-55.4331,-53.5761,-51.7192,-49.8622,-48.0052,-46.1483,-44.2913,-42.4344,-40.5774,-38.7205,-36.8635,-35.0066,-33.1496,-31.2926,-29.4357,-27.5787]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-25.7218,-23.8648,-22.0079,-20.1509,-18.294,-16.437,-14.58,-12.7231,-10.8661,-9.0092,-7.1522,-5.2953,-3.7942,-2.5808,-1.6,-0.8,0,0.8,1.6,2.5808,3.7942,5.2953,7.1522,9.0092,10.8661,12.7231,14.58,16.437,18.294,20.1509,22.0079,23.8648,25.7218,27.5787,29.4357,31.2926,33.1496,35.0066,36.8635,38.7205]}}
    ' fairbeam-data: {"mesh_lines":{"y":[40.5774,42.4344,44.2913,46.1483,48.0052,49.8622,51.7192,53.5761,55.4331,57.29,59.147,61.0039,62.8609,64.7178,66.5748,68.4318,70.2887,72.1457,74.0026,75.8596,77.7165,79.5735,81.4304,83.2874,85.1444,87.0013,88.8583,90.7152,92.5722,94.4291,96.2861,98.143,100]}}
    ' fairbeam-data: {"mesh_lines":{"z":[0,1,1.8,2.6,3.4,4.2,5,5.8,6.6,7.4,8.2,9,9.8,10.6,11.4,12.2,13,13.8,14.6,15.4,16.2,17,17.8,18.6,19.4,20.2,21,21.8,22.6,23.4,24.2,25,25.8,26.6,27.4,28.2,29,29.8,30.6,31.4]}}
    ' fairbeam-data: {"mesh_lines":{"z":[32.2,33,33.8,34.6,35.4,36.2,37,37.8,38.6,39.4,40.2,41,41.8,42.6,43.4,44.2,45,45.8,46.6,47.4,48.2,49,49.8,50.6,51.5755,52.7824,54.2753,56.1223,57.9692,59.8162,61.6631,63.5101,65.357,67.2039,69.0509,70.8978,72.7448,74.5917,76.4387,78.2856]}}
    ' fairbeam-data: {"mesh_lines":{"z":[80.1325,81.9795,83.8264,85.6734,87.5203,89.3673,91.2142,93.0611,94.9081,96.755,98.602,100.4489,102.2959,104.1428,105.9897,107.8367,109.6836,111.5306,113.3775,115.2245,117.0714,118.9183,120.7653,122.6122,124.4592,126.3061,128.1531,130]}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""electric""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gasket_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gasket_1""" + vbLf
    sCommand = sCommand + "     .Curve ""gasket_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""1"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""49"", ""-27.712813""" + vbLf
    sCommand = sCommand + "     .LineTo ""49"", ""27.712813""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gasket_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gasket_1_curve:gasket_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gasket_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gasket_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gasket_2""" + vbLf
    sCommand = sCommand + "     .Curve ""gasket_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""1"", ""-0.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""0.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""2.6"", ""0.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""2.6"", ""-0.8""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""-0.8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gasket_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gasket_2_curve:gasket_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gasket_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:gasket_1"", ""fairbeam:gasket_2""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:gasket_1 (+1)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:gasket_1"", ""gasket""" + vbLf
    AddToHistory "rename block: fairbeam:gasket_1 to: fairbeam:gasket", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port; P1/P2 lie on the port axis)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[0,0,0],"stop":[0,0,1],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=3.65)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""3.65""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=3.65)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-40""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
