' UAV printed sleeve dipole (867 MHz)
' CST-compatible VBA macro generated by Fairbeam 0.5.6 from an openEMS project
' model: sleeve-dipole-867   created: 2026-10-03T17:58:36+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=83, Y=61, Z=91.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""0.75"", ""1""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"PML_8","x+":"PML_8","y-":"PML_8","y+":"PML_8","z-":"PML_8","z+":"PML_8"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-189.8755,-180.1202,-170.3649,-160.6096,-150.8543,-141.099,-131.3437,-121.5884,-111.8331,-102.0778,-92.3225,-82.5672,-72.8119,-63.0566,-53.3013,-43.546,-33.8472,-26.0469,-20.4491,-16.4336,-13.5516,-11.4867,-10,-8.8593,-8,-7.2069,-6.6064,-6,-5.4361,-5,-4.6298,-4.1968,-3.6622,-3,-2.4283,-2,-1.6156,-1.2705,-1,-0.6667]}}
    ' fairbeam-data: {"mesh_lines":{"x":[-0.3333,0,0.3333,0.6667,1,1.2705,1.6156,2,2.4283,3,3.6622,4.1968,4.6298,5,5.4361,6,6.6064,7.2069,8,8.8593,10,11.4867,13.5516,16.4336,20.4491,26.0469,33.8472,43.546,53.3013,63.0566,72.8119,82.5672,92.3225,102.0778,111.8331,121.5884,131.3437,141.099,150.8543,160.6096]}}
    ' fairbeam-data: {"mesh_lines":{"x":[170.3649,180.1202,189.8755]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-181.4755,-171.6114,-161.7473,-151.8832,-142.0191,-132.155,-122.2909,-112.4268,-102.5627,-92.6986,-82.8345,-72.9704,-63.1063,-53.2422,-43.3781,-33.514,-24.2553,-17.4617,-12.6062,-9.1348,-6.6535,-4.8818,-3.6181,-2.7164,-2.0608,-1.6,-1.2,-0.8,-0.4,0,0.3333,0.6667,1,1.2608,1.5909,2,2.5234,3.2419,4.2336,5.6218]}}
    ' fairbeam-data: {"mesh_lines":{"y":[7.5475,10.2166,13.9204,19.0603,26.1916,35.5368,45.1594,54.782,64.4046,74.0271,83.6497,93.2723,102.8949,112.5174,122.14,131.7626,141.3852,151.0077,160.6303,170.2529,179.8755]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-253.6755,-243.6986,-233.7218,-223.7449,-213.768,-203.7912,-193.8143,-183.8375,-173.8606,-163.8838,-153.9069,-143.93,-133.9532,-123.9763,-113.9995,-104.0226,-94.1205,-86.2466,-80.6384,-76.6459,-73.8,-71.4064,-68.9968,-66.2883,-62.5452,-57.973,-53.3856,-48.7982,-44.2108,-39.6235,-35.0361,-30.4487,-25.8613,-21.2739,-16.6866,-12.7724,-9.9407,-7.8916,-6.4096,-5.3375]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-4.5626,-4,-3.5,-3,-2.5,-2,-1.5,-1,-0.5127,0.1362,1,2.0857,3.5821,5.6475,8.4968,12.4279,16.99,21.5521,26.1142,30.6763,35.2384,39.8005,44.3626,48.9247,53.4868,58.0489,62.5934,66.3059,68.9968,71.4064,73.8,76.6459,80.6384,86.2466,94.1205,104.0226,113.9995,123.9763,133.9532,143.93]}}
    ' fairbeam-data: {"mesh_lines":{"z":[153.9069,163.8838,173.8606,183.8375,193.8143,203.7912,213.768,223.7449,233.7218,243.6986,253.6755]}}
    ' fairbeam-data: {"mesh":{"cells_per_wavelength":30,"pad":99.93081933333333,"edge_rule":"thirds","max_ratio":1.4,"dielectric_cells":4,"metal_cells":6}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' board: equivalent tan d = 0.02 at 0.867 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""4.3""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.004148070674""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: board", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""board""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""board""" + vbLf
    sCommand = sCommand + "     .Xrange ""-10"", ""10""" + vbLf
    sCommand = sCommand + "     .Yrange ""-1.6"", ""0""" + vbLf
    sCommand = sCommand + "     .Zrange ""-73.8"", ""73.8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:board", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""upper_arm_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""upper_arm""" + vbLf
    sCommand = sCommand + "     .Curve ""upper_arm_curve""" + vbLf
    sCommand = sCommand + "     .Point ""1"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""69.8"", ""-5""" + vbLf
    sCommand = sCommand + "     .LineTo ""69.8"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""5""" + vbLf
    sCommand = sCommand + "     .LineTo ""1"", ""-5""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""upper_arm""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""upper_arm_curve:upper_arm""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:upper_arm", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""sleeve_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_1""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-4"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-1"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-1"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_1_curve:sleeve_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:sleeve_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""sleeve_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_2""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-69.8"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-2""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""-2""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""-8""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_2_curve:sleeve_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:sleeve_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""sleeve_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_3""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-69.8"", ""2""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""2""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""8""" + vbLf
    sCommand = sCommand + "     .LineTo ""-69.8"", ""2""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""sleeve_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""sleeve_3_curve:sleeve_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:sleeve_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:sleeve_1"", ""fairbeam:sleeve_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:sleeve_1"", ""fairbeam:sleeve_3""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:sleeve_1 (+2)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:sleeve_1"", ""sleeve""" + vbLf
    AddToHistory "rename block: fairbeam:sleeve_1 to: fairbeam:sleeve", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""coax_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""1"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coax""" + vbLf
    sCommand = sCommand + "     .Curve ""coax_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-73.8"", ""-1""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""-1""" + vbLf
    sCommand = sCommand + "     .LineTo ""-4"", ""1""" + vbLf
    sCommand = sCommand + "     .LineTo ""-73.8"", ""1""" + vbLf
    sCommand = sCommand + "     .LineTo ""-73.8"", ""-1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""coax""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""coax_curve:coax""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:coax", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""0"", ""0"", ""-1""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-1,0,-1],"stop":[1,0,1],"direction":"z"}
    ' far-field monitors at the frequencies analysed in Fairbeam
    sCommand = ""
    sCommand = sCommand + "With Monitor" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""farfield (f=0.867)""" + vbLf
    sCommand = sCommand + "     .Domain ""Frequency""" + vbLf
    sCommand = sCommand + "     .FieldType ""Farfield""" + vbLf
    sCommand = sCommand + "     .MonitorValue ""0.867""" + vbLf
    sCommand = sCommand + "     .ExportFarfieldSource ""False""" + vbLf
    sCommand = sCommand + "     .UseSubvolume ""False""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define farfield monitor: farfield (f=0.867)", sCommand

    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

End Sub
