' Wilkinson divider (2.4 GHz)
' CST-compatible VBA macro generated by Fairbeam 0.1.0 from an openEMS project
' model: wilkinson-divider   created: 2026-09-25T00:19:36+0300
'
' Run in CST: Home > Macros > Run Macro... (a new, empty 3D project is recommended).
' Every step is added to the history list, so the model can be edited and rebuilt in CST.
' Please report anything that fails to rebuild.
'
' Exported openEMS mesh lines: X=59, Y=71, Z=27.
' CST uses its own mesh; these line counts do not imply mesh or result parity.
'
' Comments starting with 'fairbeam-data:' carry the exact openEMS ports, boundaries and mesh
' settings for Fairbeam's CST macro import; CST ignores them.

Option Explicit

Sub Main ()
    Dim sCommand As String

    ' units and frequency range
    sCommand = ""
    sCommand = sCommand + "With Units" + vbLf
    sCommand = sCommand + "     .SetUnit ""Length"", ""mm""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Frequency"", ""GHz""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Time"", ""ns""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Inductance"", ""nH""" + vbLf
    sCommand = sCommand + "     .SetUnit ""Capacitance"", ""pF""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: units", sCommand

    sCommand = ""
    sCommand = sCommand + "Solver.FrequencyRange ""1"", ""4""" + vbLf
    AddToHistory "Fairbeam: frequency range", sCommand

    ' background and boundaries
    sCommand = ""
    sCommand = sCommand + "With Background" + vbLf
    sCommand = sCommand + "     .ResetBackground" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .Epsilon ""1.0""" + vbLf
    sCommand = sCommand + "     .Mu ""1.0""" + vbLf
    sCommand = sCommand + "     .XminSpace ""0""" + vbLf
    sCommand = sCommand + "     .XmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .YminSpace ""0""" + vbLf
    sCommand = sCommand + "     .YmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZminSpace ""0""" + vbLf
    sCommand = sCommand + "     .ZmaxSpace ""0""" + vbLf
    sCommand = sCommand + "     .ApplyInAllDirections ""False""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: background", sCommand

    ' fairbeam-data: {"unit_m":0.001,"boundaries":{"x-":"MUR","x+":"MUR","y-":"MUR","y+":"MUR","z-":"MUR","z+":"MUR"}}
    ' fairbeam-data: {"mesh_lines":{"x":[-18,-15.1592,-12.974,-11.293,-10,-8.9808,-7.9617,-6.9425,-5.9234,-4.9042,-3.885,-2.8659,-1.8467,-0.8276,-0.5175,-0.2588,0,0.1916,0.5175,1.2108,2.2299,3.2491,4.2682,5.2874,6.3066,7.3257,8.3449,9.364,10.3832,11.4024,12.4215,12.8018,13.0606,13.3193,13.5781,13.8368,14.4598,15.479,16.4982,16.8368]}}
    ' fairbeam-data: {"mesh_lines":{"x":[17.1531,17.4695,17.7858,18.1021,18.4185,18.7348,19.5556,20.5748,21.594,22.6131,23.6323,24.6514,25.6706,26.6898,27.7858,29.0788,30.7598,32.945,35.7858]}}
    ' fairbeam-data: {"mesh_lines":{"y":[-21.949,-19.4223,-17.4788,-15.9837,-14.8337,-13.949,-13.2491,-12.2299,-11.2108,-10.1916,-9.1724,-8.1533,-7.949,-7.6327,-7.3163,-7,-6.6837,-6.3673,-6.051,-5.5175,-5.2588,-5,-4.7412,-4.4825,-4.0766,-3.0575,-2.847,-2.5307,-2.2143,-1.898,-1.5817,-1.2653,-0.949,-0.6327,-0.3163,0,0.3163,0.6327,0.949,1.2653]}}
    ' fairbeam-data: {"mesh_lines":{"y":[1.5817,1.898,2.2143,2.5307,2.847,3.0575,4.0766,4.4825,4.7412,5,5.2588,5.5175,6.051,6.3673,6.6837,7,7.3163,7.6327,7.949,8.1533,9.1724,10.1916,11.2108,12.2299,13.2491,13.949,14.8337,15.9837,17.4788,19.4223,21.949]}}
    ' fairbeam-data: {"mesh_lines":{"z":[-4,-2.948,-2.1387,-1.5162,-1.0373,-0.669,-0.3856,-0.1677,0,0.1355,0.271,0.4065,0.542,0.6775,0.813,0.9744,1.1843,1.4572,1.8119,2.273,2.8724,3.6517,4.6648,5.9818,7.6939,9.9196,12.813]}}
    sCommand = ""
    sCommand = sCommand + "With Boundary" + vbLf
    sCommand = sCommand + "     .Xmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Ymax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmin ""expanded open""" + vbLf
    sCommand = sCommand + "     .Zmax ""expanded open""" + vbLf
    sCommand = sCommand + "     .Xsymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Ysymmetry ""none""" + vbLf
    sCommand = sCommand + "     .Zsymmetry ""none""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: boundaries", sCommand

    ' materials (openEMS loss = constant conductivity, exported as Sigma)
    ' substrate: equivalent tan d = 0.0027 at 2.4 GHz
    sCommand = ""
    sCommand = sCommand + "With Material" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .FrqType ""all""" + vbLf
    sCommand = sCommand + "     .Type ""Normal""" + vbLf
    sCommand = sCommand + "     .SetMaterialUnit ""GHz"", ""mm""" + vbLf
    sCommand = sCommand + "     .Epsilon ""3.38""" + vbLf
    sCommand = sCommand + "     .Mu ""1""" + vbLf
    sCommand = sCommand + "     .Sigma ""0.001218485329""" + vbLf
    sCommand = sCommand + "     .TanDGiven ""False""" + vbLf
    sCommand = sCommand + "     .Colour ""0.435"", ""0.604"", ""0.494""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define material: substrate", sCommand

    ' geometry
    sCommand = ""
    sCommand = sCommand + "Component.New ""fairbeam""" + vbLf
    AddToHistory "new component: fairbeam", sCommand

    sCommand = ""
    sCommand = sCommand + "With Brick" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""substrate""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""substrate""" + vbLf
    sCommand = sCommand + "     .Xrange ""-10"", ""27.785801""" + vbLf
    sCommand = sCommand + "     .Yrange ""-13.949"", ""13.949""" + vbLf
    sCommand = sCommand + "     .Zrange ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define brick: fairbeam:substrate", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""gnd_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-10"", ""-13.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""27.785801"", ""-13.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""27.785801"", ""13.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10"", ""13.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10"", ""-13.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""gnd""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""gnd_curve:gnd""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:gnd", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_1_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_1""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_1_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-10"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5175"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5175"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""-10"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_1""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_1_curve:strips_1""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_1", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_2_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_2""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_2_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-0.5175"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5175"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5175"", ""5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""0""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_2""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_2_curve:strips_2""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_2", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_3_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_3""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_3_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-0.5175"", ""4.4825""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""4.4825""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""4.4825""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_3""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_3_curve:strips_3""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_3", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_4_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_4""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_4_curve""" + vbLf
    sCommand = sCommand + "     .Point ""12.801801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_4""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_4_curve:strips_4""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_4", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_5_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_5""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_5_curve""" + vbLf
    sCommand = sCommand + "     .Point ""12.801801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""2.847""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""2.847""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_5""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_5_curve:strips_5""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_5", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_6_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_6""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_6_curve""" + vbLf
    sCommand = sCommand + "     .Point ""16.836801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""0.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_6""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_6_curve:strips_6""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_6", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_7_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_7""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_7_curve""" + vbLf
    sCommand = sCommand + "     .Point ""16.836801"", ""6.051""" + vbLf
    sCommand = sCommand + "     .LineTo ""27.785801"", ""6.051""" + vbLf
    sCommand = sCommand + "     .LineTo ""27.785801"", ""7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""6.051""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_7""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_7_curve:strips_7""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_7", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_8_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_8""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_8_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-0.5175"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5175"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""0.5175"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""0""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_8""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_8_curve:strips_8""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_8", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_9_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_9""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_9_curve""" + vbLf
    sCommand = sCommand + "     .Point ""-0.5175"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""-4.4825""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""-4.4825""" + vbLf
    sCommand = sCommand + "     .LineTo ""-0.5175"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_9""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_9_curve:strips_9""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_9", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_10_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_10""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_10_curve""" + vbLf
    sCommand = sCommand + "     .Point ""12.801801"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .LineTo ""13.836801"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""-5.5175""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_10""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_10_curve:strips_10""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_10", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_11_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_11""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_11_curve""" + vbLf
    sCommand = sCommand + "     .Point ""12.801801"", ""-2.847""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""-2.847""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""12.801801"", ""-2.847""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_11""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_11_curve:strips_11""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_11", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_12_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_12""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_12_curve""" + vbLf
    sCommand = sCommand + "     .Point ""16.836801"", ""-7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""-7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""18.734801"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""-0.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""-7.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_12""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_12_curve:strips_12""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_12", sCommand

    sCommand = ""
    sCommand = sCommand + "Curve.NewCurve ""strips_13_curve""" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""local""" + vbLf
    sCommand = sCommand + "WCS.SetNormal ""0"", ""0"", ""1""" + vbLf
    sCommand = sCommand + "WCS.SetOrigin ""0"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "WCS.SetUVector ""1"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "With Polygon" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_13""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_13_curve""" + vbLf
    sCommand = sCommand + "     .Point ""16.836801"", ""-7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""27.785801"", ""-7.949""" + vbLf
    sCommand = sCommand + "     .LineTo ""27.785801"", ""-6.051""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""-6.051""" + vbLf
    sCommand = sCommand + "     .LineTo ""16.836801"", ""-7.949""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "With CoverCurve" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .Name ""strips_13""" + vbLf
    sCommand = sCommand + "     .Component ""fairbeam""" + vbLf
    sCommand = sCommand + "     .Material ""PEC""" + vbLf
    sCommand = sCommand + "     .Curve ""strips_13_curve:strips_13""" + vbLf
    sCommand = sCommand + "     .DeleteCurve ""True""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    sCommand = sCommand + "WCS.ActivateWCS ""global""" + vbLf
    AddToHistory "define sheet: fairbeam:strips_13", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_2""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_3""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_4""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_5""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_6""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_7""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_8""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_9""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_10""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_11""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_12""" + vbLf
    sCommand = sCommand + "Solid.Add ""fairbeam:strips_1"", ""fairbeam:strips_13""" + vbLf
    AddToHistory "boolean add shapes: fairbeam:strips_1 (+12)", sCommand

    sCommand = ""
    sCommand = sCommand + "Solid.Rename ""fairbeam:strips_1"", ""strips""" + vbLf
    AddToHistory "rename block: fairbeam:strips_1 to: fairbeam:strips", sCommand

    ' ports (openEMS lumped port -> CST discrete S-parameter port, P1 = start, P2 = stop)
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""1""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""-10"", ""0"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""-10"", ""0"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 1", sCommand

    ' fairbeam-data: {"port":1,"type":"lumped","R":50,"start":[-10,-0.949,0],"stop":[-10,0.949,0.813],"direction":"z"}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""2""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""27.78580077"", ""7"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""27.78580077"", ""7"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 2", sCommand

    ' fairbeam-data: {"port":2,"type":"lumped","R":50,"start":[27.78580076808249,6.051,0],"stop":[27.78580076808249,7.949,0.813],"direction":"z","excite":false}
    sCommand = ""
    sCommand = sCommand + "With DiscretePort" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .PortNumber ""3""" + vbLf
    sCommand = sCommand + "     .Type ""SParameter""" + vbLf
    sCommand = sCommand + "     .Label """"" + vbLf
    sCommand = sCommand + "     .Impedance ""50""" + vbLf
    sCommand = sCommand + "     .Voltage ""1""" + vbLf
    sCommand = sCommand + "     .Current ""1""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""27.78580077"", ""-7"", ""0""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""27.78580077"", ""-7"", ""0.813""" + vbLf
    sCommand = sCommand + "     .InvertDirection ""False""" + vbLf
    sCommand = sCommand + "     .LocalCoordinates ""False""" + vbLf
    sCommand = sCommand + "     .Monitor ""True""" + vbLf
    sCommand = sCommand + "     .Radius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define discrete port: 3", sCommand

    ' fairbeam-data: {"port":3,"type":"lumped","R":50,"start":[27.78580076808249,-7.949,0],"stop":[27.78580076808249,-6.051,0.813],"direction":"z","excite":false}
    sCommand = ""
    sCommand = sCommand + "With LumpedElement" + vbLf
    sCommand = sCommand + "     .Reset" + vbLf
    sCommand = sCommand + "     .SetName ""r_iso""" + vbLf
    sCommand = sCommand + "     .Folder """"" + vbLf
    sCommand = sCommand + "     .SetType ""RLCSerial""" + vbLf
    sCommand = sCommand + "     .SetR ""100""" + vbLf
    sCommand = sCommand + "     .SetL ""0""" + vbLf
    sCommand = sCommand + "     .SetC ""0""" + vbLf
    sCommand = sCommand + "     .SetP1 ""False"", ""13.31930077"", ""-0.949"", ""0.813""" + vbLf
    sCommand = sCommand + "     .SetP2 ""False"", ""13.31930077"", ""0.949"", ""0.813""" + vbLf
    sCommand = sCommand + "     .SetInvert ""False""" + vbLf
    sCommand = sCommand + "     .SetMonitor ""True""" + vbLf
    sCommand = sCommand + "     .SetRadius ""0.0""" + vbLf
    sCommand = sCommand + "     .Wire """"" + vbLf
    sCommand = sCommand + "     .Position ""end1""" + vbLf
    sCommand = sCommand + "     .Create" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "define lumped element: r_iso", sCommand

    ' fairbeam-data: {"resistor":"r_iso","R":100,"start":[12.801800768082488,-0.949,0.813],"stop":[13.836800768082488,0.949,0.813],"direction":"y"}
    ' time-domain solver: steady-state limit mirrors the openEMS end criterion
    sCommand = ""
    sCommand = sCommand + "ChangeSolverType ""HF Time Domain""" + vbLf
    AddToHistory "Fairbeam: solver type", sCommand

    sCommand = ""
    sCommand = sCommand + "With Solver" + vbLf
    sCommand = sCommand + "     .SteadyStateLimit ""-60""" + vbLf
    sCommand = sCommand + "End With" + vbLf
    AddToHistory "Fairbeam: time domain solver", sCommand

    ' WARNING: lumped element r_iso: exported as a CST series RLC element (R = 100; a zero value is an absent component); openEMS spreads it over a sheet, CST uses a line
End Sub
