"""Stepped-impedance microstrip low-pass filter (5th-order Chebyshev, 0.5 dB ripple, fc = 2.5 GHz).

Design (Pozar, *Microwave Engineering*, 4th ed., sec. 8.6; ``fairbeam.analytic``):

- prototype g-values for 0.5 dB ripple, N = 5: 1.7058, 1.2296, 2.5408, 1.2296, 1.7058
- shunt capacitors -> short low-impedance lines, beta l = g Z_low / Z0
- series inductors -> short high-impedance lines, beta l = g Z0 / Z_high
- widths from the Hammerstad formulas, lengths at fc with the quasi-static eps_eff of each line

The approximation is valid for beta l < pi/4. It ignores the step discontinuities, and the lines are
not lumped elements: the real filter's cutoff sits somewhat off the prototype's and its stopband
does not fall as fast. ``analytic.cascade_lines_s`` gives the ideal distributed response for
comparison. The mesh is generated by ``Simulation.auto_mesh``.
"""

import numpy as np

from fairbeam import Param, Simulation
from fairbeam.analytic import microstrip_width, stepped_impedance_lowpass

MODEL = {
    "id": "lowpass-stepped",
    "name": "Stepped-impedance low-pass filter",
    "description": "5th-order 0.5 dB Chebyshev microstrip low-pass, fc 2.5 GHz, 20/110 ohm sections on a RO4003C-like substrate.",
    "reference": "D. M. Pozar, Microwave Engineering, 4th ed., sec. 8.6 (stepped-impedance low-pass filters)",
}

PARAMS = [
    Param("fc", 2.5, "Cutoff frequency", "GHz", minimum=0.1, maximum=30),
    Param("order", 5, "Filter order", "", minimum=1, maximum=9),
    Param("ripple", 0.5, "Passband ripple", "dB", "0 = maximally flat (Butterworth)", minimum=0, maximum=3),
    Param("z_high", 110.0, "High impedance", "ohm", minimum=60, maximum=150),
    Param("z_low", 20.0, "Low impedance", "ohm", minimum=8, maximum=40),
    Param("feed_len", 10.0, "50 Ω feed length", "mm", minimum=2, maximum=100),
    Param("sub_h", 0.813, "Substrate thickness", "mm", minimum=0.05, maximum=10),
    Param("eps_r", 3.38, "Substrate permittivity", "", minimum=1, maximum=20),
    Param("tan_d", 0.0027, "Loss tangent", "", minimum=0, maximum=0.2),
    Param("cpw", 20, "Mesh cells per wavelength", "", minimum=8, maximum=60),
    Param("f_min", 0.2, "Band start", "GHz", minimum=0.01),
    Param("f_max", 6.0, "Band stop", "GHz", minimum=0.02),
]


def build(p: dict) -> Simulation:
    f_min, f_max = p["f_min"] * 1e9, p["f_max"] * 1e9
    if f_max <= f_min:
        raise ValueError("f_max must be above f_min")
    h, er = p["sub_h"], p["eps_r"]
    secs = stepped_impedance_lowpass(p["fc"] * 1e9, p["order"], p["ripple"], 50.0, p["z_high"], p["z_low"], er, h)
    w50 = microstrip_width(50.0, er, h)
    lf = p["feed_len"]
    total = sum(s["length"] for s in secs) + 2 * lf
    wmax = max([w50] + [s["width"] for s in secs])
    x0, x1 = -total / 2, total / 2
    y_half = wmax / 2 + 6.0

    sim = Simulation(f_min, f_max, boundaries=["MUR"] * 6, max_timesteps=100000)
    sim.dielectric("substrate", er, tan_d=p["tan_d"], tan_d_freq=p["fc"] * 1e9, label="Substrate").AddBox(
        priority=0, start=[x0, -y_half, 0], stop=[x1, y_half, h])
    sim.metal("gnd", label="Ground plane").AddBox(priority=10, start=[x0, -y_half, 0], stop=[x1, y_half, 0])
    m = sim.metal("filter", label="Filter traces")
    m.AddBox(priority=10, start=[x0, -w50 / 2, h], stop=[x0 + lf, w50 / 2, h])          # input feed
    x = x0 + lf
    for s in secs:
        m.AddBox(priority=10, start=[x, -s["width"] / 2, h], stop=[x + s["length"], s["width"] / 2, h])
        x += s["length"]
    m.AddBox(priority=10, start=[x, -w50 / 2, h], stop=[x1, w50 / 2, h])                 # output feed
    sim.lumped_port(1, 50, [x0, -w50 / 2, 0], [x0, w50 / 2, h], "z", priority=5)
    sim.lumped_port(2, 50, [x1, -w50 / 2, 0], [x1, w50 / 2, h], "z", priority=5)
    sim.design = secs  # for scripts: the section list used

    # a circuit radiates little: a few mm of air instead of lambda/4, so the domain stays small
    sim.auto_mesh(cells_per_wavelength=p["cpw"], pad=12.0, metal_cells=4)
    sim.set_focus([x0 - 2, -y_half - 2, -1], [x1 + 2, y_half + 2, h + 3])
    return sim
