"""Spectrum of the DC-free Gaussian-derivative excitation."""

import re
import unittest

import numpy as np

from fairbeam.excitation import _MINUS_20_DB_RATIO, dgauss_expression, dgauss_relative_level_db


def evaluate_expression(expr: str, t: np.ndarray) -> np.ndarray:
    """Evaluate the fparser expression with numpy (only '^' differs from Python syntax)."""
    py = re.sub(r"\^", "**", expr)
    return eval(py, {"exp": np.exp, "t": t})  # noqa: S307 - expression generated by fairbeam


class ExcitationSpectrumTest(unittest.TestCase):
    F_MAX = 8e9

    def setUp(self):
        self.expr = dgauss_expression(self.F_MAX)
        f_peak = self.F_MAX / _MINUS_20_DB_RATIO
        tau = 1.0 / (np.sqrt(2.0) * np.pi * f_peak)
        self.dt = tau / 200.0
        self.t = np.arange(0.0, 20 * tau, self.dt)
        self.u = evaluate_expression(self.expr, self.t)
        n = 1 << 18
        self.spec = np.abs(np.fft.rfft(self.u, n)) * self.dt
        self.f = np.fft.rfftfreq(n, self.dt)
        self.f_peak = f_peak

    def test_unit_peak_amplitude(self):
        self.assertAlmostEqual(float(np.max(np.abs(self.u))), 1.0, places=3)

    def test_starts_and_ends_at_zero(self):
        self.assertLess(abs(self.u[0]), 1e-9)
        self.assertLess(abs(self.u[-1]), 1e-9)

    def test_zero_dc(self):
        # integral of the pulse relative to its peak spectral density
        dc = abs(np.sum(self.u) * self.dt)
        self.assertLess(dc / self.spec.max(), 1e-6)

    def test_peak_location(self):
        f_at_peak = self.f[np.argmax(self.spec)]
        self.assertAlmostEqual(f_at_peak / self.f_peak, 1.0, delta=0.01)

    def test_minus_20_db_at_f_max(self):
        level = 20 * np.log10(np.interp(self.F_MAX, self.f, self.spec) / self.spec.max())
        self.assertAlmostEqual(level, -20.0, delta=0.2)

    def test_analytic_level_matches_fft(self):
        probe = np.array([0.5e9, 1e9, 2e9, 4e9, 6e9, 8e9])
        fft_db = 20 * np.log10(np.interp(probe, self.f, self.spec) / self.spec.max())
        np.testing.assert_allclose(dgauss_relative_level_db(probe, self.F_MAX), fft_db, atol=0.05)

    def test_analytic_level_zero_at_peak(self):
        self.assertAlmostEqual(float(dgauss_relative_level_db(self.f_peak, self.F_MAX)), 0.0, places=9)


if __name__ == "__main__":
    unittest.main()
